antismash/antismash

- antismash/common/hmmer.py
- antismash/detection/cluster_hmmer/test/integration_cluster_hmmer.py
- antismash/detection/full_hmmer/test/integration_full_hmmer.py
Restricts fullhmmer and clusterhmmer to using only hmmscan results which are better than the PFAM supplied cutoffs
> common.hmmer: use trusted cutoffs on PFAM searches

- antismash/detection/hmm_detection/test/test_hmm_detection.py
Both previous pull requests tested fine individually, but the combination left this test failing with an extra argument.
> hmm_detection: fix test not caught in multi-PR merge

- Makefile
- antismash/config/args.py
- antismash/main.py
- antismash/outputs/html/top_header.html
- antismash/test/integration/integration_antismash.py
Prevents use of an output directory if it contains other content (unless --reuse is specified).
Adds a --skip-zip-file option for performance when the zip file isn't desired.
> Output directory improvements

- antismash/common/secmet/features/cds_feature.py
- antismash/common/secmet/features/cluster.py
- antismash/common/secmet/features/feature.py
- antismash/common/secmet/features/test/test_cds_feature.py
- antismash/common/secmet/features/test/test_feature.py
- antismash/common/secmet/locations.py
- antismash/common/secmet/record.py
- antismash/common/secmet/test/test_circular_conversion.py
- antismash/common/secmet/test/test_locations.py
- setup.py
Prevents potential entire-genome clusters being formed due to a gene/CDS crossing the record origin in a circular genome (e.g. in NZ_CP016793.1).
For now, this is solved by splitting any bridging features into two new features. A more thorough version will need a large rewrite of any section of code that uses a location start and end point.
Also adds a minor change to enforce clusters having a valid `contig_edge` member, though this can still be `True` in circular genomes until clusters can be formed across the bridge.
> Handle circular genome mega-clusters

- antismash/common/layers.py
- antismash/common/record_processing.py
- antismash/common/secmet/qualifiers/secmet.py
- antismash/detection/hmm_detection/__init__.py
- antismash/main.py
- antismash/modules/nrps_pks/nrps_predictor.py
- antismash/modules/nrps_pks/orderfinder.py
- antismash/outputs/html/js.py
- antismash/outputs/html/js/jnj.js
- antismash/outputs/html/js/svgene.js
- run_antismash.py
- correctly sized/drawn HTML clusters when there are many clusters
- order displayed cluster borders deterministicly
- minor cleanup of output and logging
- exit more cleanly when input files don't exist
- prevents SecMetQualifiers from having duplicate domains added when multiple cluster types would add their hits
- prevents renaming of CDS features when they only share a name with a CDS in another record
- generates monomer predictions for relevant nrpsfragment clusters
> Misc fixes

- antismash/modules/t2pks/__init__.py
- antismash/modules/t2pks/html_output.py
- antismash/modules/t2pks/test/data/GQ409537.1.gbk
- antismash/modules/t2pks/test/integration_t2pks.py
Changes the t2pks module to run by default.
Adds a test for mixed-cluster regions and non-acetyl starter units.
> Type II PKS update

- antismash/modules/lanthipeptides/specific_analysis.py
- antismash/modules/lanthipeptides/test/test_specific_analysis.py
- antismash/modules/lassopeptides/specific_analysis.py
- antismash/modules/lassopeptides/test/test_specific_analysis.py
- antismash/modules/thiopeptides/specific_analysis.py
- antismash/modules/thiopeptides/test/test_thio_specific_analysis.py
The 'start' position of a cleavage site was calculated and never used. Since all affected RiPP analyses used the beginning of the CDS translation as their leader start point anyway, the 'start' has been removed from all these functions and classes.
Also ensures that those regex-based cleavage site locators that subtract from the cleavage site position don't end up with a non-existant leader.
> RiPP cleavage fixes

- antismash/modules/nrps_pks/orderfinder.py
- antismash/modules/nrps_pks/test/test_orderfinder.py
Strictly enforces limits the size of inputs to itertools.permutations, since that's O(n!).
Some timings from a run of the maximum size from my machine:
nrps_pks module total, including non-relevant sections: 153s  (with profiling active, 101s without)
generation of orders (with itertools): 17s  (of which sorting them is 13s)
ranking the generated orders: 108s
The ranking can easily be parallelised in the future when we have a little more time, but for now this will prevent hitting swap and crashing.
> NRPS PKS ordering fix

- antismash/common/logs.py
- antismash/common/secmet/features/feature.py
- antismash/common/secmet/features/test/test_cds_feature.py
- antismash/common/secmet/locations.py
- antismash/common/secmet/record.py
- antismash/common/secmet/test/test_locations.py
- antismash/common/test/test_logs.py
- antismash/main.py
For 6,000 refseq assemblies run, the vast majority of errors were due to some unexpected locations:
- point locations where the start and end are the same are now allowed (e.g. `138^139`)
- the cross-origin feature split has been tweaked to avoid fragments with less than three bases (e.g. `join(2813..2849, 1)`
- programmed frameshifts backwards into the previous location part (e.g. `join(156..168, 168..200)`) no longer are mistakenly detected as crossing the origin (this was the only issue, location operations on these worked fine)
Another issue was that using logfiles in sequential runs within the same process caused file descriptor leaks, so logging setup has been reworked into a context manager to ensure it properly cleans up the changes it made and the open log file handler.
> Fixes from refseq minimal runs

- antismash/common/secmet/features/antismash_feature.py
- antismash/common/secmet/features/feature.py
- antismash/common/secmet/features/test/test_domain.py
- antismash/common/secmet/features/test/test_feature.py
- antismash/common/secmet/locations.py
- antismash/common/secmet/test/test_locations.py
- antismash/download_databases.py
- antismash/modules/sactipeptides/specific_analysis.py
- antismash/modules/t2pks/t2pks_analysis.py
- antismash/modules/t2pks/test/test_analysis.py
Fixes a few small issues:
- t2pks wasn't filtering correctly, so features with interesting domain combinations could cause KeyErrors
- there was an off-by-one error with sublocation bounds checks
- AntismashFeatures/Domains could be created with translations that contained stop codons
- sactipeptides would attempt to run hmmsearch on nothing, which hmmsearch doesn't like
The lack of codon start for translation creation and sequence extraction caused some issues. NCBI's genbank examples codon_start Looking at how biopython's `SeqFeature.translate()` [here](https://github.com/biopython/biopython/blob/c1f0f643a58db1b2fbf057d6875e8e41e6c0a73a/Bio/SeqFeature.py#L340) handles the `codon_start` qualifier, I've gone with simply trimming the offset from the start of the location for the duration …
> Fixes from refseq default runs

- antismash/common/layers.py
- antismash/modules/clusterblast/core.py
- antismash/modules/clusterblast/results.py
- antismash/modules/clusterblast/svg_builder.py
- antismash/modules/clusterblast/test/data/Z18755.3.gbk
- antismash/modules/clusterblast/test/integration_clusterblast.py
- antismash/outputs/html/index.html
Reference clusters that only had one gene/CDS were always being discarded (e.g. ZZ18755 hitting BGC0000342) during scoring. This is fixed by removing the requirement for at least two hits for those reference clusters that don't have that many features.
Also adds the reference cluster type to the clusterblast SVG output and the HTML overview.
> Clusterblast improvements

- antismash/modules/lanthipeptides/test/data/epicidin_280.gbk
- antismash/modules/lanthipeptides/test/data/epidermin.gbk
- antismash/modules/lanthipeptides/test/data/labyrinthopeptin.gbk
- antismash/modules/lanthipeptides/test/data/lactocin_s.gbk
- antismash/modules/lanthipeptides/test/data/lanthipeptide.gbk
- antismash/modules/lanthipeptides/test/data/microbisporicin.gbk
- antismash/modules/lanthipeptides/test/data/nisin.gbk
- antismash/modules/lanthipeptides/test/data/sco_cluster3.gbk
- antismash/modules/lanthipeptides/test/integration_lanthipeptides.py
- antismash/modules/lassopeptides/test/data/SSV2083.gbk
- antismash/modules/lassopeptides/test/data/burhizin.gbk
- antismash/modules/sactipeptides/test/data/AP012495.1_c14.gbk
- antismash/modules/sactipeptides/test/data/AP012495.1_c14_missing_precursor.gbk
- antismash/modules/thiopeptides/test/data/CP009369.1.gbk
- antismash/modules/thiopeptides/test/data/lac_before_analysis.gbk
- antismash/modules/thiopeptides/test/data/nosi_before_analysis.gbk
- antismash/modules/thiopeptides/test/data/thiopeptide.gbk
- antismash/modules/thiopeptides/test/data/thiostrepton_before_analysis.gbk
- antismash/modules/thiopeptides/test/integration_thiopeptides.py
This PR isn't fixing anything, but is necessary for simplifying planned changes to the `sec_met` annotations and any other future detection annotation changes.
Previously the RiPP integration tests used detection annotations in genbanks to avoid failing when detection modules had issues. This causes problems when detection gets out of sync, with the genbanks needing to be regenerated each time detection changes.
This PR removes this shortcut of detection and runs the detection on each cluster. This does make the integration tests take a little longer, but on my machine all RiPP module tests (unit and integration) take a total of 85 seconds, which I think is still reasonable.
> Run full analyses in RiPP tests

- antismash/common/hmm_rule_parser/cluster_prediction.py
- antismash/common/record_processing.py
- antismash/common/secmet/features/cds_feature.py
- antismash/common/secmet/features/test/test_cds_feature.py
- antismash/common/secmet/features/test/test_supercluster.py
- antismash/common/secmet/qualifiers/secmet.py
- antismash/common/secmet/qualifiers/test/test_secmet.py
- antismash/detection/cassis/test/test_cassis.py
- antismash/detection/genefunctions/test/integration_smcogs.py
- antismash/modules/sactipeptides/specific_analysis.py
- antismash/modules/smcog_trees/test/integration_smcogs.py
Cleans up the last of the antiSMASH 4 style `sec_met` annotations.
`/sec_met="Kind: biosynthetic"` never changed, so it was removed and replaced with `/gene_kind="..."`, containing the `GeneFunction` type as provided by `CDSFeature.gene_function`. The name might be better as something else. The related attribute was also removed from `SecMetQualifier`.
`/sec_met="Type: ..."` was misleading, since a CDS doesn't have a type in the way that it was used. Since all information that was contained in this is contained in the `/gene_functions` annotation, this was  dropped and removed from `SecMetQualifier`.
`/sec_met="Domains detected: ..."` was very noisy, but since it's the only remaining annotation from `SecMetQualifier`, it has been changed have each domain in a list of `/sec_met_domain` …
> sec_met/gene_functions annotation cleanup

- antismash/modules/clusterblast/core.py
- antismash/modules/clusterblast/test/test_clusterblast.py
The clusterblast reference protein list is meant to be 6 fields separated by pipe characters. However, some of the annotation fields in the list contain pipe characters and caused part of the annotation field to be included in the name, which then broke after hits were detected using the real name.
This PR adds support for (and tests for) pipe characters within the annotation field.
When the clusterblast database is next regenerated, this might be made redundant.
> Handle bad reference protein lines in clusterblast

- antismash/modules/nrps_pks/html_output.py
- antismash/modules/nrps_pks/nrps_predictor.py
- antismash/modules/nrps_pks/orderfinder.py
- antismash/modules/nrps_pks/parsers.py
- antismash/modules/nrps_pks/smiles_generator.py
- antismash/modules/nrps_pks/test/integration/integration_nrps_pks.py
- antismash/modules/nrps_pks/test/test_nrps_predictor.py
Calculates how good a match the stach prediction is and combines it with the SVM prediction when at least 80% of a match to the predicted monomer.
Also allows for multiple predictions from the stach section instead of treating pipe-joined combinations as a single prediction and stops `-` always being treated as a joining character between monomers.
> Combine Stachelhaus predictions in NRPS consensus

- antismash/modules/smcog_trees/test/integration_smcogs.py
There was an issue specific to testing where the SMCoG tree generation tests failed due to the HMMer databases not being built at the time of the test. This depended on exactly how the tests were run and even in what order tests were run.
This PR fixes the problem by including the `genefunctions` data preparation as part of the `smcog_trees` test setup (since `smcog_trees` reuses on the `genefunctions.smcog` data).
> smcogs_trees: ensure data files are pressed before attempting the tests

- antismash/common/secmet/errors.py
- antismash/common/secmet/features/antismash_feature.py
- antismash/common/secmet/features/cds_feature.py
- antismash/common/secmet/features/feature.py
- antismash/common/secmet/features/gene.py
- antismash/common/secmet/features/pfam_domain.py
- antismash/common/secmet/features/prepeptide.py
- antismash/common/secmet/features/test/test_feature.py
- antismash/common/secmet/record.py
- antismash/common/secmet/test/test_secmet.py
- antismash/outputs/html/js.py
Fixes some minor issues in secmet:
- protein inputs caused failures when processing CDS features, now caught at the beginning of record conversion
- qualifier dictionaries from BioPython could contain None as a valid value, so handling of that was corrected
- `Gene` and specifically `Gene.is_pseudo()` could be simplified since the qualifier was more easily detectable
- two format strings were incorrectly tuples
- made pylint a little happier with the `CDSFeature` init
This PR also changes some errors raised by secmet to more accurately indicate that the problem is with the input records, such as the protein input case mentioned earlier.
> Secmet fixes

- setup.py
As far as I can tell, no piece of code imports these libraries.
None of our code imports 'scipy' either, but installing 'scikit-learn' fails if 'scipy' isn't there.
> chore: Remove unused install dependencies

- antismash/__main__.py
- antismash/common/hmm_rule_parser/cluster_prediction.py
- antismash/common/hmm_rule_parser/rule_parser.py
- antismash/common/hmm_rule_parser/test/test_rule_parser.py
- antismash/common/path.py
- antismash/common/secmet/features/cds_feature.py
- antismash/common/secmet/features/test/test_domain.py
- antismash/common/secmet/features/test/test_feature.py
- antismash/common/secmet/qualifiers/secmet.py
- antismash/common/secmet/record.py
- antismash/common/secmet/test/test_secmet.py
- antismash/common/test/test_path.py
- antismash/detection/cassis/promoters.py
- antismash/detection/genefunctions/test/integration_smcogs.py
- antismash/main.py
- antismash/modules/clusterblast/results.py
- antismash/modules/nrps_pks/smiles_generator.py
- antismash/modules/nrps_pks/test/test_smiles_generator.py
- antismash/modules/smcog_trees/__init__.py
- antismash/modules/smcog_trees/trees.py
- setup.py
- fixes a number of small style and safety issues
- adds a context manager for changing directories `common.path.changed_dir()`
- adds a `RELATED` field to detection rules as a first step to indicating which profiles are of interest to a rule even when not required for cluster detection
- silences the matplotlib debug logging in `modules.smcog_trees` if running with debug on
- logs the current antiSMASH version to make logfiles a little more useful in finding which version they were created with when full output fails
> Style and cleanup pass

- antismash/common/secmet/features/__init__.py
- antismash/common/secmet/features/antismash_domain.py
- antismash/common/secmet/features/antismash_feature.py
- antismash/common/secmet/features/cds_feature.py
- antismash/common/secmet/features/cds_motif.py
- antismash/common/secmet/features/domain.py
- antismash/common/secmet/features/feature.py
- antismash/common/secmet/features/gene.py
- antismash/common/secmet/features/pfam_domain.py
- antismash/common/secmet/features/prepeptide.py
- antismash/common/secmet/features/test/test_domain.py
- antismash/common/secmet/locations.py
- antismash/common/secmet/test/test_locations.py
There was an assumption throughout the code that `CompoundLocation` was a subclass of `FeatureLocation`. This was a faulty assumption.
The main issue was some type checking inside `common.secmet`, but those remaining location functions that didn't explicitly handle `CompoundLocation` have also been altered.
> Compound inheritance correction

- antismash/common/test/test_utils.py
- antismash/common/utils.py
- antismash/modules/lanthipeptides/specific_analysis.py
- antismash/modules/lanthipeptides/test/integration_lanthipeptides.py
- antismash/modules/lanthipeptides/test/test_specific_analysis.py
- antismash/modules/sactipeptides/test/integration_sactipeptides.py
There were two issues causing precursors to score below their expected values from antiSMASH 4:
- a distance calculation used `-` when it should have used `+`, this affected lanthi-, lasso- and sactipeptides
- lanthipeptide precursor scoring was being based on the domains found within all the precursor candidates instead of the cluster itself
There were also two other small issues found in the lanthipeptides module that were fixed at the same time:
- signature scores were being truncated to ints from floats
- if a signature match could not be found, the regex version reported a score of `0` instead of the minimum threshold for signature matches of `-100`
> Fix missing RiPP precursors

- antismash/common/gff_parser.py
- antismash/common/secmet/features/cds_feature.py
- antismash/common/secmet/features/feature.py
- antismash/common/secmet/features/test/test_cds_feature.py
- antismash/common/secmet/test/helpers.py
- antismash/common/secmet/test/test_secmet.py
Improves handling of awkward translations:
- catches more bad translation content (similar to #85, allows `X`)
- ensures translations aren't longer than the location can support (with exceptions for ambiguous positions)
- removes the gff_parser's translation generation in favour of the CDSFeature's
- protein position conversions of overly long translations with ambiguous positions no longer cause issues (e.g. MPTA5024_04555 from AWEV00000000.1)
Due to NCBI records inferring the amino from partial nucleotides, the length of a translation is allowed to extend beyond the location only when the end position (or start, for the reverse strand) is an extendable position (`AfterPosition` for forward strand, `BeforePosition` for reverse strand). In these cases, when a protein coordinate conversion …
> Ambiguous translations

- antismash/modules/clusterblast/core.py
- antismash/modules/clusterblast/test/test_clusterblast.py
Reference clusters in the clusterblast database (from `clusterblast_20170105_v8_31.tar.xz`) have a listing of locus tags and protein ids. For 28 of those clusters (of ~220,000), the database is missing details of one or more proteins (e.g. `DF820425` and protein `GAJ32366`, presumably due to sharing a locus tag with `GAJ32367`). This caused crashes when those particular clusters had hits *and* were in the top scores.
Until such point as the clusterblast database is regenerated and these issues are removed, this PR fixes the problem by removing the offending clusters, along with any proteins they contained. Any hits against those removed proteins will be ignored.
The runtime cost is around 2 seconds on my machine per load of the database. Running diamond on the database will take a few …
> Handle errors in clusterblast database

- antismash/outputs/html/templates/overview.html
Turns out this only improves things if the rest of your layout is fully
responsive, which the antiSMASH results page isn't.
This reverts commit 941d19e8588b91509ac0f7b476ef47502df4c275.
> Revert "html: handle ipads and phones better"

- antismash/common/gff_parser.py
- antismash/common/hmm_rule_parser/rule_parser.py
- antismash/common/hmmer.py
- antismash/common/record_processing.py
- antismash/common/secmet/features/cds_feature.py
- antismash/common/secmet/features/cluster.py
- antismash/common/secmet/features/feature.py
- antismash/common/secmet/features/region.py
- antismash/common/secmet/features/supercluster.py
- antismash/common/secmet/features/test/test_cds_feature.py
- antismash/common/secmet/features/test/test_feature.py
- antismash/common/secmet/record.py
- antismash/common/test/test_record_processing.py
- antismash/detection/hmm_detection/cluster_rules.txt
- antismash/detection/nrps_pks_domains/domain_identification.py
- antismash/modules/lanthipeptides/specific_analysis.py
- antismash/outputs/html/generator.py
- antismash/test/integration/data/nisin_postdetection.gbk
Another collection of small fixes:
- running on region genbank outputs no longer causes missing cluster issues
- more input exceptions are caught and reraised as `AntismashInputError`s
- improved CDS naming checks
- better error messages for missing CDSMotifs
- fixed result and record syncing with inputs containing empty records
- improve rule tokenisation error messages for cluster rules
- allow general text in COMMENT fields of rules
- fixes a case where lanthipeptides could have precursor details without a valid class
Edited to add:
- places where sub-CDS domain translations were created now slice the CDS translation instead of regenerating from the record sequence, important for when valid translations are initially provided
> More fixes

- antismash/config/default.cfg
- antismash/detection/nrps_pks_domains/domain_drawing.py
- antismash/detection/nrps_pks_domains/templates/details.html
- antismash/modules/clusterblast/html_output.py
- antismash/modules/clusterblast/templates/clusterblast.html
- antismash/modules/clusterblast/templates/knownclusterblast.html
- antismash/modules/clusterblast/templates/subclusterblast.html
- antismash/modules/lanthipeptides/html_output.py
- antismash/modules/lanthipeptides/templates/details.html
- antismash/modules/lanthipeptides/templates/sidepanel.html
- antismash/modules/lassopeptides/html_output.py
- antismash/modules/lassopeptides/templates/details.html
- antismash/modules/lassopeptides/templates/sidepanel.html
- antismash/modules/nrps_pks/html_output.py
- antismash/modules/nrps_pks/templates/monomers.html
- antismash/modules/nrps_pks/templates/products.html
- antismash/modules/sactipeptides/html_output.py
- antismash/modules/sactipeptides/templates/details.html
- antismash/modules/sactipeptides/templates/sidepanel.html
- antismash/modules/t2pks/html_output.py
- antismash/modules/t2pks/templates/sidepanel.html
- antismash/modules/thiopeptides/html_output.py
- antismash/modules/thiopeptides/templates/details.html
- antismash/modules/thiopeptides/templates/sidepanel.html
- antismash/outputs/html/generator.py
- antismash/outputs/html/templates/header.html
- antismash/outputs/html/templates/overview.html
- antismash/outputs/html/templates/regions.html
Adds a help tooltip to every panel of the output HTML, including one for each module tab. Where possible, the tooltips also link to the docs website for further details.
> Help tooltips

- antismash/detection/cassis/__init__.py
This keeps the more relevant "Detecting gene cluster regions using CASSIS" in the job status
for the web service.
> cassis: Downgrade two INFO level log lines to DEBUG

- antismash/common/secmet/record.py
- antismash/common/secmet/test/test_secmet.py
Also removes the old `unique_id` attribute since it wasn't actually unique for splice variants or duplicate RiPP precursors.
> secmet: handle duplicate CDS naming for splice variants

- antismash/common/hmm_rule_parser/cluster_prediction.py
- antismash/common/hmm_rule_parser/rule_parser.py
- antismash/common/hmm_rule_parser/test/test_rule_parser.py
In an `AndCondition`, if one part was satisfied by one CDS and other parts
were satisfied by other CDSs, information was lost when other parts
were only satisfied due to the presence of a separate successful part
e.g.
`A --8kb-- X --8kb-- B` with a rule like `X and minimum(2, [A, B])` with a cutoff of 10kb.
if the minimum condition alone would fail due to distance, but the X
condition succeeds, only the CDS for X would be marked as core, despite
the whole cluster still being created.
Since `A and X and B` would result in the same 16kb cluster, allowing the `MinimumCondition` to extend by the cutoff to each side of an anchor in the same way seems the best way to solve it.
The behavior of finding clusters is unchanged, this fix just ensures that all components responsible for finding the …
> Rules fix for MinimumConditions in an AndCondition

- antismash/common/module_results.py
- antismash/common/record_processing.py
- antismash/common/test/test_record_processing.py
- simplifies catching protein record inputs
- ensures record identifiers are sanitised before they are used in genefinding
- raise an error if all input records will be skipped
- minor improvement typing annotations for `DetectionResults`
> More small fixes

- antismash/detection/hmm_detection/cluster_rules/strict.txt
> hmm_detection: Move cycdipepsynth from 'other' to more specific 'CDPS' rule

- antismash/config/args.py
> args: Print the correct version in the help output.

- antismash/common/subprocessing.py
Allows for official java instead of just openjdk.
> subprocessing: fix java version testing

- antismash/common/gff_parser.py
- antismash/common/record_processing.py
- antismash/common/secmet/features/feature.py
- antismash/common/secmet/locations.py
- antismash/common/secmet/record.py
- antismash/common/secmet/test/test_circular_conversion.py
- antismash/common/secmet/test/test_locations.py
- antismash/common/secmet/test/test_secmet.py
- antismash/common/test/test_gff_parser.py
- antismash/common/test/test_record_processing.py
- antismash/detection/genefinding/run_glimmerhmm.py
- antismash/main.py
Some input errors weren't properly being wrapped as input errors for the purposes of logging. Some inputs were also not being caught as errors.
New constraints:
- exons can no longer overlap beyond a single amino frameshift
- only two (CDS and gene) features can cross the origin in a circular record
- no features can cross the origin in a linear record
- features must be fully contained by the provided sequence
Better reporting:
- completely unordered exons are caught instead of reporting a split location as crossing the origin after that stage of processing was complete
- all known input errors are now logged (I'm sure there'll be something, somewhere that still sneaks through)
- error messages for features missing locations now include "invalid" in the message, since Biopython likes to …
> Improved input validation and error reporting

- antismash/common/record_processing.py
- refactors the new strict parsing into a separate function
- adds the biopython warning `Couldn't parse feature location: 'omplement(23931..28567)'` to the list of warnings raised as exceptions
> Convert more biopython warnings to exceptions

- antismash/common/secmet/locations.py
- antismash/common/secmet/test/test_locations.py
Some NCBI records have overlapping exons of 10 bases or more, so the restriction has to be relaxed. This relaxes the check to ensure that no two exons are sharing a stop codon.
> secmet: simplify overlapping exons check to shared stop codons

- antismash/config/executables.py
- antismash/config/test/test_executables.py
Also adds `Fasttree` as an alternative binary name, since that's what their own install/compile instructions use.
Fixes both the false positive prereq check and the binary naming from #157
> Fix executable missing paths being present in config object

- antismash/common/secmet/features/subregion.py
- antismash/common/secmet/features/test/test_subregion.py
- antismash/common/secmet/test/helpers.py
- antismash/detection/cassis/__init__.py
- antismash/detection/cassis/test/test_cassis.py
- antismash/outputs/html/js.py
- removes a bunch of print statements that were left behind in CASSIS at some point
- changes `SubRegion`'s  `anchor` attribute/parameter to `label` to be more generic, since incoming sideloaded annotations and `anchor` don't really make sense
> Style pass

- antismash/common/subprocessing/hmmpfam.py
The `cpus` option is present in help, even when it would cause exits. This instead looks for the error message `FATAL: Posix threads support is not compiled into HMMER; --cpu doesn't have any effect`  when hmmpfam2 fails, rerunning without the cpus option.
> Improve handling of hmmpfam2 compiled without threading support

- antismash/common/secmet/features/protocluster.py
- antismash/common/secmet/features/region.py
- regions were changing from 1-index to 0-index feature numbering when adjusting for the region-specific details
- protocluster cores were missing the tool=antismash qualifier that meant they weren't properly being treated as a feature created by antismash on parsing
> Genbank fixes

- antismash/outputs/html/generate_html_table.py
While playing with #180 I triggered the error message below. This is due to trying to write to a directory that doesn't  exists. Simply creating the directory manually and re-running antismash worked like a charm.  So i have changed to code to `os.makedirs` which acts like `mkdir -p` and I've used the `exist_ok=True` flag to not cause an error if the directory exists.  Therefore this should not change any behavior except in the case of a missing recursive directory which will now be created instead of throwing an error. 
os.makedirs docs [for reference](https://docs.python.org/3/library/os.html?highlight=os%20makedirs#os.makedirs)
Note: this came up in the context of the `--reuse-results` CLI flag. In the normal case these directories would have been created by the modules.
```bash
File …
```
> Use os.makedirs instead of os.mkdir

- antismash/common/secmet/features/candidate_cluster.py
- antismash/common/secmet/features/candidate_cluster/__init__.py
- antismash/common/secmet/features/candidate_cluster/formation.py
- antismash/common/secmet/features/candidate_cluster/structures.py
- antismash/common/secmet/features/candidate_cluster/test/test_candidate_cluster.py
- antismash/common/secmet/features/candidate_cluster/test/test_formation.py
- antismash/common/secmet/features/cdscollection.py
- antismash/common/secmet/features/feature.py
- antismash/common/secmet/features/test/test_candidate_cluster.py
- antismash/common/secmet/features/test/test_feature.py
There's a few instances of orphaned protoclusters or incorrect candidate cluster types when a protocluster is fully contained within another. A protocluster fully contained by a chemical hybrid could be orphaned if it was also part of the hybrid. Protoclusters fully contained by the neighbourhood of another protocluster could result in both being 'single' candidate clusters instead of the larger being a 'neighbouring' candidate.
The cause of this was due to candidate formation using only a single pass through for all types, which, while fast, wasn't accurate in this situation. The fix here is to change to a multi-pass creation step, forming all chemical hybrids before moving on to interleaved, and so on. The multi-pass logic is slower, but in tests on my machine the change is from 1ms to …
> Fix issues with protoclusters fully contained by others

- antismash/test/integration/integration_antismash.py
- antismash/test/test_antismash.py
- pytest.ini
- setup.py
Newest versions of `pytest` are incompatible with `coverage` leading to coverage like shown here:
To avoid this, compatible `pytest` versions have been restricted to avoid version 5+, at least until it's no longer a problem.
Other test changes:
- better silencing of warnings (e.g. numpy silences some Cython warnings, pytest unsilenced them)
- shifted a unit test that could result in calling external programs to integration tests
> Testing fixes

- antismash/common/secmet/features/cds_feature.py
- antismash/common/secmet/qualifiers/secmet.py
- antismash/common/secmet/qualifiers/test/test_secmet.py
- antismash/common/secmet/record.py
- antismash/config/args.py
- antismash/detection/hmm_detection/__init__.py
- antismash/modules/lanthipeptides/templates/details.html
- antismash/modules/lanthipeptides/templates/sidepanel.html
- antismash/modules/lanthipeptides/test/integration_lanthipeptides.py
- antismash/modules/lassopeptides/templates/details.html
- antismash/modules/lassopeptides/templates/sidepanel.html
- antismash/modules/nrps_pks/templates/monomers.html
- antismash/modules/sactipeptides/templates/details.html
- antismash/modules/sactipeptides/templates/sidepanel.html
- antismash/outputs/html/css/style.scss
- antismash/outputs/html/templates/cds_detail.html
- antismash/outputs/html/templates/overview.html
New:
- adds `hmm_detection`'s strictness level to both log and HTML (the HTML version is very simple, for now)
- all CDS names in HMTL use serif fonts to avoid `l`/`I` issues
Fixes:
- some outdated docstring
- slight oddness in HTML when viewed with MS Edge
- CDS `secmet` qualifier parsing being too strict on whitespace
- improved error messages and handling for:
- command line arguments referring to paths
- translations of sequences that are invalid
- invalid feature locations
> Small fixes and tweaks

- antismash/common/secmet/features/candidate_cluster/formation.py
- antismash/common/secmet/features/candidate_cluster/test/test_formation.py
When multiple protoclusters were fully contained by a hybrid group but didn't contribute to it, sorting by neighbourhood start could cause the first of the protoclusters to be skipped.
> Fix candidate cluster creation

- antismash/common/secmet/features/candidate_cluster/formation.py
- antismash/common/secmet/features/candidate_cluster/test/test_formation.py
Interleaved cluster formation was using a list sorted by `core_location` in an inner loop, but not the outer loop (instead using `location`, which includes the neighbourhood), leading to early breaks and interleaved clusters being skipped (though singles/neighbouring would still be created).
> secmet: fix inconsistent sorting in interleaved candidate construction

- antismash/detection/nrps_pks_domains/module_identification.py
Based on feedback at the 1st European Fungal Natural Products Symposium.
> nrps_pks_domains: Identify fungal non-reducing PKS product template (PT) domains

- antismash/common/hmmer.py
- antismash/modules/clusterblast/__init__.py
- antismash/test/integration/integration_antismash.py
When some prerequisites were missing, they might still get used to check other prereqs (e.g. HMMer databases were pressed). This ensures that `--check-prereqs` doesn't crash out with errors in the process.
> Better handling of missing executables when checking prereqs

- antismash/common/gff_parser.py
- antismash/common/hmm_rule_parser/cluster_prediction.py
- antismash/common/secmet/features/feature.py
- antismash/common/secmet/features/module.py
- antismash/common/secmet/features/test/test_feature.py
- antismash/common/secmet/features/test/test_module.py
- antismash/common/secmet/record.py
- antismash/detection/genefinding/run_glimmerhmm.py
- antismash/detection/genefinding/test/integration_glimmerhmm.py
- antismash/detection/nrps_pks_domains/domain_drawing.py
- antismash/outputs/html/js.py
Better input handling:
- records named `.` no longer cause a crash after running glimmerhmm
- negative coordinates no longer permitted (also prevents creation of some empty translations)
- improved error handling on badly formatted GFF inputs
Visualisation:
- resistance indicators shown again in HTML
- module lids replace `X` substrates with `?` as per the original version (lost after change from `nrp` to `X`)
Also adds a getter for pairings of substrate and monomer to `secmet.Module` features.
> Misc small fixes

- antismash/detection/nrps_pks_domains/module_identification.py
- antismash/detection/nrps_pks_domains/test/test_modules.py
PKS modules without a PKS_KS should be considered complete if they are the first module in a CDS.
NRPS modules without a Condensation were being considered complete even if they weren't the first module in a CDS.
> Improve NRPS/PKS module completeness checks

- antismash/common/external/rodeo_svm/svm_classify.py
- antismash/common/record_processing.py
- antismash/common/secmet/features/antismash_feature.py
- antismash/common/secmet/features/test/test_antismash_domain.py
- antismash/modules/lanthipeptides/rodeo.py
- antismash/modules/lassopeptides/specific_analysis.py
- antismash/modules/sactipeptides/specific_analysis.py
- antismash/modules/thiopeptides/rodeo.py
- antismash/outputs/html/css/style.scss
- setup.py
When domain names are too long for a single line in a genbank qualifier, they introduce a whitespace which causes the `from_biopython()` conversion of an NRPS/PKS module feature to raise an error about unknown domain names.
This fix removes whitespace in domain names when converting from biopython to be consistent.
Two other tiny fixes are included:
- better reporting of which record is at fault if a protein record is detected
- removes some duplicate CSS definitions
> Handle genbank format introducing whitespace in domain names

- antismash/common/external/rodeo_svm/svm_classify.py
- antismash/common/secmet/features/cds_feature.py
- antismash/common/secmet/features/test/test_cds_feature.py
- antismash/common/secmet/qualifiers/nrps_pks.py
- antismash/common/secmet/qualifiers/test/test_nrpspks.py
A few small code changes to fix some recent issues.
- fixes #246 by focusing on only the relevant parts of the version information
- fixes the conda-specific #237 where multiprocessing handles a class inheriting from list differently than standard python installs
- improves the error message generated when a CDS `transl_table` qualifier is invalid
> Small fixes

- antismash/detection/hmm_detection/cluster_rules/strict.txt
CP001511 contains a transAT cluster around 5k to 30k, as described in
https://doi.org/10.1002/ange.201709056
This was missed with the rules that required an ATd domain.
AB088224 is another example of a transAT without an ATd.
> hmm_detection: find more transAT-PKS clusters

- antismash/config/executables.py
When installed from source (or homebrew), the fasttree executable is called FastTree, not Fasttree
> config: fix alternative fasttree executable spelling

- antismash/common/record_processing.py
- antismash/common/test/test_record_processing.py
- antismash/config/args.py
Implements #217 
Using `--allow-long-headers` will avoid renames for record accessions/names that are too long. The behaviour for invalid characters within those names is unchanged.
> common.record_processing: conditionally allow long record identifiers

- antismash/detection/clusterfinder_probabilistic/__init__.py
- antismash/detection/clusterfinder_probabilistic/test/test_clusterfinder.py
Fixes #251 
The adding of subregions is handled in [antismash.main](https://github.com/antismash/antismash/blob/master/antismash/main.py#L173), but clusterfinder also had a separate add, which is removed with these changes.
> clusterfinder: fix subregions being added twice

- antismash/modules/thiopeptides/specific_analysis.py
- antismash/modules/thiopeptides/test/data/NZ_CP015439_section.gbk
- antismash/modules/thiopeptides/test/integration_thiopeptides.py
Previous thiopeptide tests didn't have a case where a small ORF was found extra to the annotations existing at the beginning of the thiopeptide analysis. This meant that there was a bug in results regeneration that wasn't being found by the tests.
> thiopeptides: fix results regeneration for extra ORFs

- antismash/outputs/html/__init__.py
- antismash/outputs/html/templates/overview.html
Resolves #294 by adding a command line option (`--html-start-compact`) to set the default view for the overview page to compact.
> html: add an option to start the overview in compact mode

- antismash/common/record_processing.py
- antismash/common/secmet/features/region.py
- antismash/common/secmet/features/test/test_region.py
- antismash/common/secmet/record.py
- antismash/common/secmet/test/test_circular_conversion.py
- antismash/common/secmet/test/test_secmet.py
- antismash/common/serialiser.py
- antismash/common/test/helpers.py
- antismash/common/test/test_record_processing.py
- antismash/modules/pfam2go/test/test_pfam2go.py
- antismash/modules/tta/test/test_tta.py
- setup.py
Handle latest biopython versions without Alphabet, makes the minimum biopython 1.78.
Also bumps minimum python to 3.7 to match language features used elsewhere.
> Handle removal of biopython\s Alphabet in newer versions

- antismash/common/secmet/features/antismash_domain.py
- antismash/common/secmet/features/test/test_antismash_domain.py
- antismash/common/secmet/record.py
- antismash/common/secmet/test/test_secmet.py
- antismash/detection/nrps_pks_domains/__init__.py
- antismash/detection/nrps_pks_domains/domain_identification.py
- antismash/detection/nrps_pks_domains/modular_domain.py
- antismash/detection/nrps_pks_domains/test/integration_domains.py
- antismash/detection/nrps_pks_domains/test/test_modular_domain.py
- antismash/modules/active_site_finder/__init__.py
- antismash/modules/active_site_finder/analysis.py
- antismash/modules/active_site_finder/test/test_analysis.py
- antismash/modules/nrps_pks/nrps_predictor.py
- antismash/modules/nrps_pks/parsers.py
- antismash/modules/nrps_pks/results.py
- antismash/modules/nrps_pks/specific_analysis.py
- antismash/modules/nrps_pks/substrates.py
As discussed in #288, there needed to be a more generic way of handling `aSDomain` features annotated in GenBank files.
Subclasses of `AntismashDomain` can now be registered by modules creating them and registered as a variant for specific regeneration (via `antismash.common.secmet.features.antismash_domain.register_asdomain_variant()`).
After registration, `AntismashDomain.from_biopython()` will use the relevant type based on the `aSTool` qualifier matching the registered type. If no tool matches, the generic `AntismashDomain` will be used.
Previous NRPS/PKS-specific attributes are now handled by the `antismash.detection.nrps_pks_domains.ModularDomain` class.
> Change AntismashDomain to be more generic and subclassable by modules for specifics

- antismash/common/hmm_rule_parser/cluster_prediction.py
- antismash/common/hmm_rule_parser/rule_parser.py
- antismash/common/hmm_rule_parser/test/test_cluster_prediction.py
- antismash/common/hmm_rule_parser/test/test_rule_parser.py
- antismash/detection/hmm_detection/__init__.py
- antismash/detection/hmm_detection/categories.py
- antismash/detection/hmm_detection/cluster_rules/loose.txt
- antismash/detection/hmm_detection/cluster_rules/relaxed.txt
- antismash/detection/hmm_detection/cluster_rules/strict.txt
- antismash/detection/hmm_detection/data/categories.json
- antismash/detection/hmm_detection/test/test_hmm_detection.py
The idea here is that we can use the actual cluster rules to build the database's `bgc_types.sql` at some point in future.
> Add secmet rule categories

- antismash/common/hmm_rule_parser/cluster_prediction.py
- antismash/common/hmm_rule_parser/test/test_cluster_prediction.py
Previously, nearly all rules with `SUPERIORS` specified were single CDS features and wouldn't create overlapping protoclusters. With the addition of the new RiPP rules, especially the `RRE-containing` rule, the previous method of filtering out 'inferior' types where the inferior was completely contained by the superior was insufficient and has been changed to be overlapping with any superior type.
> common.hmm_rule_parser: remove inferiors on overlap, not just contains

- antismash/common/secmet/features/feature.py
- antismash/common/secmet/features/test/test_feature.py
- antismash/common/secmet/record.py
- antismash/common/secmet/test/test_secmet.py
- antismash/common/serialiser.py
- antismash/common/test/test_serialiser.py
- antismash/detection/genefinding/__init__.py
- antismash/outputs/html/__init__.py
The JSON output now includes a list of areas for each record, where previously they were derived from the other contents of the JSON. This should simplify things for people wanting something similar to the old spreadsheet style result and having to script it. 
This change is write-only so while the schema version is bumped (to 2), previous schema versions can still be reused with `--reuse-results`.
Other fixes:
- improves handling of some odd ways of specifying codon starts
- hides the pyScss Deprecation/FutureWarnings about nested sets, as users were thinking that was an error (can be removed when/if pyScss updates)
- changes the `ValueError` raised when `--genedfinding-tool` is set to `error` (the default), to a `AntismashInputError` so that the error message is displayed and the …
> Misc small additions and fixes

- antismash/common/record_processing.py
- antismash/common/test/integration_mac_bug.py
- antismash/common/test/test_record_processing.py
- antismash/custom_typing.pyi
Beginning in python 3.8 on macOS `multiprocessing.Pool` started using `spawn()` instead of `fork()`, which broke the singleton behaviour with `get_config()`. This only affected `record_processing` calling the gene finding detection module.
This fixes this specific issue by reconstructing the relevant options within the function needing them in the case that that the config object is empty.
Fixes #360
> Handle bug in macOS py3.8+ changes to parallel functions and config

- antismash/common/secmet/features/cds_feature.py
- antismash/common/secmet/features/feature.py
- antismash/common/secmet/features/test/test_cds_feature.py
- antismash/common/secmet/features/test/test_feature.py
- antismash/common/secmet/locations.py
- antismash/common/secmet/test/test_locations.py
This fixes a bug that only affects CDS features that have no annotated translation (or the annotation is invalid) and have a frameshift (via the `codon_start` qualifier).
Locations were being adjusted correctly to account for the shift, but that adjustment was taking place _after_ a translation was extracted, leading to incorrect translations being generated. If no stop codon was found in the incorrect translation, it could end up being one amino too long and cause failures if a HMMer hit landed at the very last position.
Fixes #377
> secmet: fix translation generation of frameshifted CDSes

- antismash/detection/nrps_pks_domains/domain_identification.py
- antismash/detection/nrps_pks_domains/test/test_domain_identification.py
It was possible for NRPS/PKS modules to be formed when the genes in question weren't sequential. This is now fixed.
This also incidentally fixes a crash in the bubbles visualiser that occurred when a module like this was generated and crossed candidate cluster boundaries,
> Fix incorrect merging of cross-CDS NRPS/PKS modules

- antismash/common/secmet/features/feature.py
- antismash/common/secmet/features/test/test_module.py
- antismash/common/secmet/record.py
- antismash/common/secmet/test/test_secmet.py
> secmet: Fix locus tag duplicates even if the conflicting CDSes only overlap with a gene feature of the same name

- antismash/download_databases.py
- antismash/modules/cluster_compare/data/build_cluster_compare.py
With the addition of new NRPS/PKS profiles and changes to how NRPS/PKS modules are detected, and many other changes, the accuracy of the clustercompare comparisons was decreasing.
This PR uses the current master of antiSMASH on MIBiG JSON as at `2.0-11abfec` to regenerate the comparison database.
Some fixes for the database generation are also included:
- gene function now only considers detection-stage gene function annotations
- subclasses of `Other` category MIBiG entries no longer build with mistaken comma joins for each character in the subclass
- the `--mibig` build option now takes a file with accessions to include, to more easily separate pending and active entries that may reside in the same input directory
> ClusterCompare MIBiG database update

- antismash/common/secmet/record.py
> secmet: Reduce the risk of crc32 collisions in duplicate CDS location detection

- antismash/common/secmet/features/antismash_domain.py
- antismash/common/secmet/features/antismash_feature.py
- antismash/common/secmet/features/cds_feature.py
- antismash/common/secmet/features/cds_motif.py
- antismash/common/secmet/features/feature.py
- antismash/common/secmet/features/gene.py
- antismash/common/secmet/features/pfam_domain.py
- antismash/common/secmet/features/prepeptide.py
- antismash/common/secmet/features/test/test_feature.py
- antismash/detection/nrps_pks_domains/modular_domain.py
- antismash/detection/tigrfam/tigr_domain.py
- antismash/modules/rrefinder/rre_domain.py
Long CDS names (e.g. AB366635.1 with a `gene` qualifier of `MIPLSYAQRRMWFINRFEGPSSTYNIPLLLRFHGSLDTAALRAAFQDVLV`) are line wrapped by biopython output when using a longer qualifier name, and when those are read back in with biopython it keeps a single space where the line break was.
This PR changes all `locus_tag` qualifier parsing in features that need to point at CDS features to remove any spaces found.
> secmet: handle biopython introducing spaces into locus tags

- antismash/main.py
By default the NamedTemporaryFile has 0600 permissions, change to 0644 after copying to the outdir to match the other files.
> main: Make sure the output zipfile has sane permissions

- antismash/modules/nrps_pks/orderfinder.py
Mixed use of `<` and `<=` let edge cases through to hit an assertion later on.
> nrps_pks: fix off by one in orderfinder domain docking limit

- antismash/common/secmet/locations.py
- antismash/common/secmet/record.py
- antismash/common/secmet/test/test_locations.py
- antismash/common/secmet/test/test_secmet.py
Some NCBI annotations of Pfam hits can end up with very strange locations, e.g. this from `AM743169.1`, where the parent CDS location is `complement(join(3683384..3684415,3684417..3686921))`
```
misc_feature    complement(order(3683871..3684154,3683813..3684415))
/locus_tag="Smlt3626"
/inference="protein motif:HMMPfam:PF02518"
/note="HMMPfam hit to PF02518, Histidine kinase-, DNA
gyrase B-, and HS, score 3.6e-44"
/pseudo
```
This PR removes any of these redundant exons to avoid triggering the origin-crossing detection logic.
> secmet: handle bad NCBI misc features for Pfam hits

- antismash/modules/cluster_compare/html_output.py
This reliably happens when a region contains no protoclusters, but the comparison config includes one of the protocluster search modes (e.g. via sideloading). The javascript data already has this condition, which led to javascript errors attempting to access missing information because the selector still existed.
Existing code in the HTML template handles the case for when all search modes have no results.
> cluster_compare: don't create HTML content for search types with no results

- antismash/common/pfamdb.py
- antismash/detection/genefunctions/__init__.py
Fixes an edge case where one was doing development work with `make clean` and `--database-dir` was using the `databases` directory in the source tree rather than in another location.
> Fix some database dir HMMs not being repressed when necessary

- antismash/detection/nrps_pks_domains/domain_drawing.py
- antismash/outputs/html/css/style.scss
- antismash/outputs/html/test/test_generation.py
Also includes a couple of small fixes for test file creation and deduplication of domain sequences in NRPS/PKS domain tooltips.
> Update NAPDOS links to v2, and other small changes

- antismash/common/test/test_record_processing.py
- antismash/config/args.py
Also rename the option to just 'long_headers'
> config: Allow long headers by default

- antismash/modules/nrps_pks/stachelhaus.py
I thought I'd caught this in the previous PR and removed it, but I'd removed a _different_ print.
> nrps_pks: remove a stray print from stachelhaus

- antismash/detection/hmm_detection/cluster_rules/strict.txt
- antismash/outputs/html/css/secmet.scss
Renamed siderophore rule to NRPS-independent-siderophore, to match the name of the biosynthetic pathway rather than the biological function (10.1080/10409238.2018.1476449)
split from https://github.com/antismash/antismash/pull/514
Sorry for the mixup 😬
> hmm_detection: rename siderophore rule to NRPS-independent siderophore

- antismash/common/secmet/features/cdscollection.py
- antismash/common/secmet/features/protocluster.py
- antismash/common/secmet/features/test/test_cdscollection.py
- antismash/common/secmet/features/test/test_protocluster.py
- antismash/common/secmet/test/helpers.py
- antismash/common/test/helpers.py
Since the first rule with a cutoff larger than it's neighbourhood was introduced in #487, it was possible for a protocluster to lie on the edge of a record and have looked _past_ the edge for part of the rules, but it still wouldn't count as being on the contig edge. That could lead to some misleading reports.
This PR changes contig edge calculations for protoclusters to use the largest of cutoff and neighbourhood ranges, and parent `CDSCollection`s now check the state of all child collections.
> Contig edge detection improvements

- antismash/detection/nrps_pks_domains/domain_drawing.py
- antismash/modules/nrps_pks/test/integration/integration_nrps_pks.py
In 4ece39d74 I changed the name of the NRPS/PKS substrate consensus key, but didn't update it in the drawing logic, which disabled, by default, the showing of module lids with substrates even when there were substrates predicted for modules.
This PR fixes that and changes the tests to catch similar issues in future.
> nrps_pks_domains: fix default state of modules showing domains

- antismash/common/comparippson/__init__.py
- antismash/common/comparippson/analysis.py
- antismash/common/comparippson/test/test_analysis.py
- antismash/detection/nrps_pks_domains/domain_drawing.py
- antismash/detection/nrps_pks_domains/templates/details.html
- antismash/main.py
- antismash/modules/lanthipeptides/html_output.py
- antismash/modules/lassopeptides/html_output.py
- antismash/modules/sactipeptides/html_output.py
- antismash/modules/tfbs_finder/html_output.py
- antismash/modules/thiopeptides/html_output.py
- antismash/outputs/html/__init__.py
- antismash/outputs/html/css/style.scss
- antismash/outputs/html/generator.py
- antismash/outputs/html/visualisers/bubble_view.py
- antismash/outputs/html/visualisers/templates/bubble_view.html
Updates HTML tooltips for:
- NRPS/PKS tabs to include links to the module visualisation(s) docs page (and point at an existing rule for PKSs)
- TFBS to link to the relevant docs page
- RiPP modules to link to the CompaRiPPson docs page
Also tweaks CompaRiPPson HTML output to sort groups by descending similarity, then descending group size, then accession name. This makes more common sequences more obvious.
Also bumps the version to "beta" state.
> Small HTML tweaks and a version bump to beta

- antismash/common/hmm_rule_parser/cluster_prediction.py
- antismash/common/hmm_rule_parser/rule_parser.py
- antismash/common/hmm_rule_parser/structures.py
- antismash/common/hmm_rule_parser/test/test_cluster_prediction.py
- antismash/common/hmm_rule_parser/test/test_rule_parser.py
- antismash/detection/hmm_detection/__init__.py
- antismash/detection/hmm_detection/test/test_hmm_detection.py
Adds command line options for setting multipliers for rule cutoff and neighbourhood sizes for fungal inputs (bacterial inputs remain at 1.0):
```
--hmmdetection-fungal-cutoff-multiplier HMMDETECTION_FUNGAL_CUTOFF_MULTIPLIER
Sets the multiplier for rule cutoffs in fungal inputs (default: 1.0).
--hmmdetection-fungal-neighbourhood-multiplier HMMDETECTION_FUNGAL_NEIGHBOURHOOD_MULTIPLIER
Sets the multiplier for rule neighbourhoods in fungal inputs (default: 1.5).
```
Note the default fungal neighbourhood multiplier being 1.5.
> Fungal protocluster size multipliers

- antismash/modules/nrps_pks/orderfinder.py
- antismash/modules/nrps_pks/test/integration/integration_nrps_pks.py
- antismash/modules/nrps_pks/test/test_orderfinder.py
Fixes finding a final gene for the order when thioesterases and other terminal domains were in a cross-CDS module.
Tweaks the order finding itself to bias towards keeping consecutive genes together.
> PKS order finding tweaks

- antismash/common/hmm_rule_parser/cluster_prediction.py
- antismash/common/hmm_rule_parser/test/test_cluster_prediction.py
- antismash/common/secmet/features/candidate_cluster/formation.py
- antismash/common/secmet/features/candidate_cluster/test/test_formation.py
- antismash/common/test/helpers.py
A example was discovered of genes being marked as core genes without being contained by a protocluster core, like so:
The gene above overlaps with it's neighbour by 10 bases. It's considered a core gene for a protocluster type not present, but both of the protoclusters present are superiors to the missing protocluster.
There were two separate issues causing this to happen, both of which are handled by this pull request.
1. It was possible for a protocluster to be lost during candidate cluster creation, due to the deduplication process using only coordinates. This meant that the interleaved candidate that would have contained the missing protocluster was being dropped, orphaning the protocluster and resulting in it being discarded.
This was fixed by including the product list in the …
> Fixes for rule superior/inferior edge cases

- .github/workflows/pylint_issue_reporter.yml
Updates the linting action dependencies to fix the deprecation warnings.
Also renames the action slightly to make it clearer in the checks section of a PR.
> chore: update workflow dependencies

- antismash/config/args.py
For being more explicit about it's possible use in documentation, an alternative name would be useful. The old name needs to stay for legacy reasons as well as being a valid name for checking prerequisite binaries.
> config: add a '--prepare-data' alias for '--check-prereqs' option

- antismash/common/html_renderer.py
- antismash/common/test/test_html_renderer.py
- antismash/config/__init__.py
- antismash/outputs/html/generator.py
- antismash/outputs/html/test/test_generation.py
* Allows additional directories to be provided to HTML template classes to ease reuse of antiSMASH HTML templates/macros
* Moves the template directory construction to using a constant, so it's able to be overridden if necessary
* Adds a default value for the `triggered_limit` member of the config object, to prevent it from not existing when later required in the case of antiSMASH's record processing not being used
> Better support for using antiSMASH as a library

- antismash/download_databases.py
Renames 6 profiles to more accurately match the transATor data.
> download_databases: fix names/descriptions of some transATor profiles

- antismash/common/secmet/features/region.py
Fixes the cluster genbank data, which currently looks like this:
COMMENT     ##antiSMASH-Data-START##
Version      :: 7.0.0beta1-ba3cf6d6
Run date     :: 2023-02-27 13:28:17
NOTE: This is a single region extracted from a larger record!
Orig. start  :: {self.location.start}
Orig. end    :: {self.location.end}
{comment_end_marker}##
> Add missing f-string prefix

- antismash/detection/hmm_detection/dynamic_profiles/cyanobactin_precursor.py
- antismash/detection/hmm_detection/dynamic_profiles/test/test_cyanobactin_precursor.py
Under very specific conditions, the cyanobactin dynamic profile could walk off the end of the translation due to the length check being off by one. This PR fixes that.
> hmm_detection: fix off by one in cyanobactin dynamic profile

- antismash/detection/nrps_pks_domains/module_identification.py
> nrps_pks_domains: Also identify TauD dioxygenase domains

- antismash/modules/nrps_pks/nrpys.py
- antismash/modules/nrps_pks/test/test_nrpys.py
This fixes the many unclear predictions for e.g. the CDA cluster.
> nrps_pks: Go with best 8 Å match if multiple Stachelhaus matches for the same stach signature exist

- antismash/common/secmet/features/candidate_cluster/formation.py
- antismash/common/secmet/features/candidate_cluster/structures.py
- antismash/common/secmet/features/candidate_cluster/test/test_formation.py
- antismash/common/secmet/features/cds_feature.py
In some rare circumstances, it was possible for protoclusters to be lost. This typically happened on contig edges, when a cluster was considered "interleaved" but only had a very minor overlap, such that a candidate that had the same coordinates as another would've been created but was being dropped, which also potentially dropped one or more protoclusters.
This PR fixes the known cases of these lost protoclusters by "promoting" any orphaned protocluster into the more strict type that already existed at those coordinates. For these protoclusters that are promoted, a SINGLE candidate cluster will also be created, unless there's already another stronger candidate cluster at those specific coordinates as well (likely only to happen on contig boundaries).
A related change is that it is no …
> Further fixes for lost protoclusters

- antismash/common/secmet/record.py
The order of these features matters because this will affect the order of features in the generated GenBank file. Some tools, like bioconvert, rely on the gene feature being the first feature for every location.
> secmet: List genes before other features in Record.get_all_features()

- antismash/main.py
For versioning of development builds, the git hash is already included, so it is less confusing to have just `7.dev-<hash>` than a version which may not exist (e.g. `6.2.0-<hash>` as existed some time ago).
> chore: change version from future versions to 'dev'

- antismash/main.py
Currently the last message in verbose mode before `antiSMASH status: SUCCESS` is `Running [some module]`.
> Add info-level message "Writing results"

- antismash/common/subprocessing/diamond.py
- antismash/common/subprocessing/test/test_diamond.py
Only provide --threads to diamond command when it isn't a 'version' subcommand. 
The 'version' subcommand (breaks with v diamond 2.1.7) will  give these errors:
```
$ diamond version
diamond version 2.1.7
$ diamond version --threads 2
Error: Option is not permitted for this workflow: threads
$ diamond version --tmpdir /scratch/
Error: Option is not permitted for this workflow: tmpdir
```
> Fix: diamond version subcommand fails with --threads 

- antismash/common/comparippson/data/build_data.py
- antismash/common/record_processing.py
- antismash/common/secmet/features/module.py
- antismash/common/serialiser.py
- antismash/common/test/test_record_processing.py
- antismash/common/test/test_serialiser.py
- antismash/config/args.py
- antismash/detection/hmm_detection/cluster_rules/strict.txt
- antismash/detection/nrps_pks_domains/domain_identification.py
- antismash/detection/nrps_pks_domains/test/test_domain_identification.py
- antismash/main.py
- antismash/modules/cluster_compare/html_output.py
- antismash/modules/nrps_pks/html_output.py
- antismash/modules/nrps_pks/orderfinder.py
- antismash/modules/nrps_pks/templates/monomers.html
- antismash/modules/nrps_pks/test/test_orderfinder.py
- antismash/support/genefinding/run_glimmerhmm.py
- antismash/support/genefinding/run_prodigal.py
Changes:
- Adds a pair of options `--abort-on-invalid-records` (the default) and `--no-abort-on-invalid-records`. The default behaviour is unchanged, but the `no-abort` version will allow runs to simply discard invalid records and continue on those that remain valid
- Improves reporting of some input parsing failures where biopython itself crashes
- Renames the "NRPS/PKS monomers" sidepanel tab in the HTML output to "NRPS/PKS substrates", as only the unmodified substrates are shown
- Rewords the lanthipeptide rules to have consistent description style in order to simplify scraping of those files for uses other than antiSMASH
- Removes the `id` field from JSON output of records which weren't ever used and resulted in a great deal of `id="<unknown id>"` repetition bloating the file size …
> Misc small changes

- antismash/config/args.py
- antismash/detection/hmm_detection/__init__.py
- antismash/detection/sideloader/__init__.py
Currently, the default `-h` output does not show that users can access the complete list of antiSMASH options with `--help-showall`.
Therefore, `--help-showall` was added to a new arg group 'Help options' that shows on `-h`.
Because there was no class for non module-related arg groups, a new class _SimpleArgs was created.
This class allows core options to be printed without immediately printing the list of analysis toggles (which is done by the ModuleArgs class).
Also:
- Adds a short form, `-t`, for `--taxon`
- Moves `--databases` flag from advanced to basic options
- Puts sideload and hmm detection options in seperate arg groups
> Improve help options

- antismash/common/comparippson/data/build_data.py
For some reason, on both Python 3.9 and 3.10 on _some_ systems, `mypy` (specifically 0.982, the pinned version) complains about missing attributes in the CompaRiPPson data script. Converting those imports/references from direct access (e.g. `antismash.modules.lassopeptides`) to `from antismash.modules import ...` avoids the issue.
> comparippson: work around mypy issue

- antismash/detection/hmm_detection/cluster_rules/relaxed.txt
When creating the methanobactin rule, which uses DUF692 *and* another profile, the DUF692 profile was removed, resulting in some previously detected RiPP-likes no longer being found.
> hmm_detection: return DUF692 to RiPP-like, since methanobactin is more specific

- .github/workflows/pylint_issue_reporter.yml
- antismash/common/comparippson/data/build_data.py
- antismash/common/record_processing.py
- antismash/common/secmet/features/module.py
- antismash/common/serialiser.py
- antismash/common/subprocessing/diamond.py
- antismash/common/subprocessing/test/test_diamond.py
- antismash/common/test/test_record_processing.py
- antismash/common/test/test_serialiser.py
- antismash/config/args.py
- antismash/detection/hmm_detection/__init__.py
- antismash/detection/hmm_detection/cluster_rules/relaxed.txt
- antismash/detection/hmm_detection/cluster_rules/strict.txt
- antismash/detection/nrps_pks_domains/domain_identification.py
- antismash/detection/nrps_pks_domains/test/test_domain_identification.py
- antismash/detection/sideloader/__init__.py
- antismash/main.py
- antismash/modules/cluster_compare/html_output.py
- antismash/modules/clusterblast/test/integration_clusterblast.py
- antismash/modules/nrps_pks/html_output.py
- antismash/modules/nrps_pks/orderfinder.py
- antismash/modules/nrps_pks/templates/monomers.html
- antismash/modules/nrps_pks/test/test_orderfinder.py
- antismash/support/genefinding/run_glimmerhmm.py
- antismash/support/genefinding/run_prodigal.py
Prepares for bugfix release 7.0.1, which fixes some issues identified in antiSMASH 7.0.0 and adds some small quality of life features:
* Fixes issues involving newer diamond versions (2.1 and above)
* Fixes some cross-CDS module behaviour in NRPS/PKS regions
* Fixes a possible crash when record names are extremely long
* Fixes a regression in the `RiPP-like` detection rule causing some clusters to be undetected
* Fixes lassopeptides being omitted from CompaRiPPson database generation
* Improves JSON output size by removing noisy unused fields
* Improves help output
* Improves reporting for some invalid input errors
* Improves miscellaneous descriptions (including detection rules, logging, and HTML output)
* Adds an option to drop invalid records and continue processing remaining records …
> Update stable to 7.0.1

- setup.py
Somehow this was missing in the changes to 7.0, but we've been using Python 3.9 features for quite a while now.
Should fix #641
> chore: bump minimum python version to 3.9

- antismash/common/hmm_rule_parser/cluster_prediction.py
- antismash/common/hmm_rule_parser/rule_parser.py
- antismash/common/hmm_rule_parser/test/test_rule_parser.py
- antismash/common/secmet/locations.py
- antismash/common/secmet/test/helpers.py
- antismash/common/secmet/test/test_locations.py
- antismash/detection/hmm_detection/cluster_rules/strict.txt
- antismash/detection/hmm_detection/test/test_hmm_detection.py
Introduces new syntax for a detection rule section: `EXTENDERS <CDSCondition>`
The example use case is kirromycin, which is a TransAT-PKS. The current rule is
```
RULE transAT-PKS
CATEGORY PKS
DESCRIPTION Trans-AT polyketide
EXAMPLE NCBI CP006259.1 382565-499230 kirromycin
EXAMPLE NCBI CP001511.1 5000-30000 toblerol
CUTOFF 45  # kirromycin (CP006259) has a range of ~42kb
NEIGHBOURHOOD 20
CONDITIONS cds(PKS_AT and not ANY_KS)
and (
cds(ATd and ANY_KS)
or cds(tra_KS and PP-binding)
)
```
Previously, the cutoff for this rule had to be enlarged to 45kb to reach all the KS-containing CDSes. Some newer, more extreme cases were found where the distance from the last transAT module was 131kb away from the CDS with the AT domain. Making the cutoff that large would be problematic, so this …
> Add extension options for detection rules

- antismash/detection/hmm_detection/cluster_rules/strict.txt
Also fix a copy/paste issue in the DOI link
> hmm_detection: The rule detects hydrogen cyanide, not hydroxycyanide

- antismash/common/serialiser.py
- antismash/detection/cluster_hmmer/__init__.py
- antismash/detection/tigrfam/__init__.py
- antismash/modules/nrps_pks/data/aaSMILES.txt
Both TigrFAM and ClusterHMMer used very silly ways of generating feature lists, these have been changed to use the functionality provided by the `Record` class. The results aren't affected.
As the JSON results serialiser changes introduced in c2d08646 were just a small addition that regenerate, the compatible schema list has been bumped. This won't likely have much affect on most use cases of actual results reuse as rulesets have changed, but there are some edge cases where it's useful.
The SMILES for the `cap` substrate have been rearranged so the backbone ordering is consistent with other substrates.
> Small tweaks

- antismash/modules/clusterblast/clusterblast.py
- antismash/modules/clusterblast/core.py
- antismash/modules/clusterblast/known.py
- antismash/modules/clusterblast/sub.py
These are generally misleading for people, who expect these to be the output of the analysis and not the raw hits. As such, it would be better if they were removed, especially given the file sizes that can be reached.
> clusterblast: remove raw diamond output files

- antismash/common/hmm_rule_parser/cluster_prediction.py
- antismash/common/hmm_rule_parser/rule_parser.py
- antismash/common/hmm_rule_parser/structures.py
- antismash/common/hmm_rule_parser/test/helpers.py
- antismash/common/hmm_rule_parser/test/test_categories.py
- antismash/common/hmm_rule_parser/test/test_cluster_prediction.py
- antismash/common/signature.py
- antismash/detection/hmm_detection/__init__.py
- antismash/detection/hmm_detection/test/integration_hmm_detection.py
- antismash/detection/hmm_detection/test/test_hmm_detection.py
This is a collection of code cleanup, performance optimisations, and flexibility.
The code has been cleaned up and more easily navigated by bundling all relevant options into a `Ruleset` class; these include the rules themselves, the categories and signature information those rules refer to, and so on.
For fragmented inputs or inputs of many genomes, the rule parser caches these new `Ruleset` instances, meaning any particular combination of rules and multipliers will only ever have to be parsed once globally instead of once per contig. This won't help single well assembled chromosomes, but should help uses like metagenomic and fungal inputs.
As for extra flexibility, by taking advantage of the `Ruleset`s bundling things, it's trivial to add a limitation via code or the command line on …
> Combine detection information into a single "Ruleset"

- antismash/common/secmet/record.py
- antismash/common/secmet/test/test_secmet.py
- antismash/common/serialiser.py
- antismash/common/test/test_serialiser.py
- antismash/main.py
- antismash/outputs/html/templates/regions.html
Around 25% of the time spent in HTML generation, including when using `--reuse`, was spent calculating the GC content of records. This was largely due to repeatedly calculating it in a loop over regions within the record within the HTML template that generates each region view.
Even after moving the repetition out of the loop, it's still a repeated calculation, as the TTA module will use it along with the HTML output module. To fix this, `Record` now caches the value after it's been calculated once.
To go even further, this doesn't even need to be calculated at all when using `--reuse` if the value is kept in the JSON results. That's fixed by adding a `gc_content` field to the JSON records, and the required infrastructure to pass that through to `Record`'s init and also …
> HTML generation optimisation

- antismash/detection/sideloader/__init__.py
- antismash/detection/sideloader/data_structures.py
- antismash/modules/cluster_compare/html_output.py
Two issues related to subregions caused poor results in ClusterCompare when comparing against MIBiG hits:
1. CDS features with hits to rule detection profiles were not annotated when only in a sideloaded subregion and not a protocluster. This was due to sideloaded annotations being added _after_ the detection ran. This caused ClusterCompare to be missing components when the region in question had a subregion (e.g. all of the MIBiG antiSMASH-generated pages).
The fix was moving the sideloaded detection to the "full genome" stage prior to the "area formation stage".
2. The "Protocluster to Region" view for the ClusterCompare visualisation deliberately omits subregions since they aren't protoclusters. The "Region to Region" view is more accurate in that case. Since all antiSMASH-generated …
> Tweaks for ClusterCompare

- antismash/modules/clusterblast/svg_builder.py
- antismash/outputs/html/templates/cds_detail.html
Fixes #666 by removing ambiguous location markers from SVGs and links.
Adds a new link in the gene details panel of HTML output that blasts the gene against the antiSMASH-DB (version 4.0 only).
> antiSMASH-DB fixes/updates

- antismash/__main__.py
- antismash/common/comparippson/data/build_data.py
- antismash/download_databases.py
- antismash/modules/clusterblast/svg_builder.py
Having generated the database outputs with recent antiSMASH versions also fixes #596
> Update antiSMASH-DB data for version 4.0

- .github/CODEOWNERS
- .gitignore
- .pylintrc
- antismash/common/secmet/features/abstract.py
- antismash/common/secmet/features/cds_feature.py
- antismash/common/secmet/features/cdscollection.py
- antismash/common/secmet/features/region.py
- antismash/common/secmet/features/test/test_cdscollection.py
- antismash/common/secmet/locations.py
- antismash/common/secmet/record.py
- antismash/common/secmet/test/test_secmet.py
- antismash/modules/nrps_pks/nrpys.py
Optimisations:
* Location containment checks were using the biopython `__contains__`, which is slower than just checking bounds
* `Record` and `CDSCollection` instances rebuilt their `CDSFeature` sets every time they were fetched, they now cache the results, with the cache being marked dirty whenever a new CDS is added
Cleanup:
* Included output directories and any typical input files within the root of the repo to the list of ignored files
* Upgrades pylint's `unused-import` warnings to errors
* Adds an assertion to try to catch a very rare case of 34AA signatures being shown instead of 10AA Stachelhaus signatures
> Misc optimations and cleanup

- antismash/common/pfamdb.py
If `hmmpress` is terminated early, the broken database will pass `ensure_database_pressed` because all four `.h3x` files are immediately created. This leads to a `RuntimeError` during analysis.
Now, `ensure_database_pressed` checks that `h3x` file size is greater than zero.
> common: ensure that pressed HMM database files are not empty

- .github/workflows/unwanted_files.yml
- .gitignore
Adds a pull request check (trivially extendable to include pushes as well) that finds and lists any files that match ignore filters.
To avoid bypassing this (intentionally or accidentally) via first modifying `.gitignore`, the default branch's `.gitignore` will be used over the one in the pull request itself.
> Enforce ignored files not being present in pull requests

- antismash/common/gff_parser.py
- antismash/common/hmm_rule_parser/cluster_prediction.py
- antismash/common/record_processing.py
- antismash/common/secmet/features/candidate_cluster/structures.py
- antismash/common/secmet/locations.py
- antismash/common/secmet/record.py
- antismash/common/secmet/test/helpers.py
- antismash/common/subprocessing/blast.py
- antismash/common/test/test_gff_parser.py
- antismash/common/test/test_record_processing.py
- antismash/detection/cassis/__init__.py
- antismash/detection/sideloader/test/test_general.py
- antismash/main.py
- antismash/modules/tta/test/test_tta.py
- antismash/modules/tta/tta.py
- setup.cfg
- setup.py
- Bumps minimum python version from 3.9 to 3.11 to allow for new features which simplify future development (e.g. the `Self` type).
- Bumps `mypy` from 0.982 to 1.9.0, along with associated fixes for existing types
- Bumps `biopython` from 1.78 to 1.81, along with associated fixes
- Bumps `bcbio-gff` from 0.70 to 0.71 (which required a biopython newer than 1.78), fixing some issues with GFF inputs
> Dependency version upgrades

- antismash/common/secmet/features/cds_feature.py
- antismash/common/secmet/features/test/test_cds_feature.py
In cases where a CDS feature had no identifiers (`locus_tag`, `gene`, `protein_id`), names are autogenerated using the location. When the location had ambiguous positions, the resulting name included the string representation of that position, e.g. `cds<123_456`, which causes issues in HTML/CSS.
This change removes the ambiguous marker from the name, resulting in `cds123_456`. This may collide with other unidentified CDS features at the same coordinates without ambiguous positions, but that is an issue best solved by correcting the annotations before they hit antiSMASH.
> secmet: fix CDS feature name generation breaking CSS/HTML output

- antismash/common/secmet/__init__.py
- antismash/common/secmet/features/__init__.py
- antismash/common/secmet/features/cdscollection.py
- antismash/common/secmet/features/module.py
- antismash/common/secmet/features/prepeptide.py
- antismash/common/secmet/features/region.py
- antismash/common/secmet/features/source.py
- antismash/common/secmet/features/test/test_cdscollection.py
- antismash/common/secmet/features/test/test_module.py
- antismash/common/secmet/locations.py
- antismash/common/secmet/record.py
- antismash/common/secmet/test/helpers.py
- antismash/common/secmet/test/test_secmet.py
- antismash/common/subprocessing/prodigal.py
- antismash/config/__init__.py
- antismash/config/test/test_args.py
- antismash/detection/sideloader/general.py
- antismash/main.py
- antismash/modules/lassopeptides/specific_analysis.py
- antismash/modules/rrefinder/test/test_rrefinder.py
- antismash/modules/sactipeptides/specific_analysis.py
- antismash/support/genefinding/__init__.py
- antismash/support/genefinding/run_prodigal.py
- antismash/support/genefinding/test/integration_prodigal.py
- antismash/support/genefinding/test/test_prodigal.py
- antismash/test/test_antismash.py
A collection of small changes, most of which are simple fixes or improvements. The remainder are aimed at supporting future use cases or use as a library (e.g. adding `subprocessing.prodigal` runners.
- Improves some testing helpers, and performance for various areas.
- Improves communication of `--sideload-by-cds` with a name that does not exist in inputs. As no mechanism exists (yet) for checking all records with all options, for now this just logs a warning.
- Adds explicit tracking of `source` features in records, for future use in multi-source inputs.
- Fixes an issue in lassopeptide scoring where checking that another component was within a certain distance would never fail.
- Fixes an issue with some very specific NRPS/PKS module constructs resulting in crashes due to unexpected …
> Small fixes and improvements

- antismash/detection/nrps_pks_domains/module_identification.py
- antismash/detection/nrps_pks_domains/test/test_modules.py
- antismash/modules/nrps_pks/data/aaSMILES.txt
- antismash/modules/nrps_pks/orderfinder.py
- antismash/modules/nrps_pks/parsers.py
A more complete version of #720. 
- adds SMILES for all predictions made for what's loaded by CAL domains
- treats CAL domains and starter domains and loader domains so that the module itself can count as a starter module
- adds support for monomer modification if dehydrogenase domains are present in the module (the only affected substrate is `AHBA`)
- treats modules with CAL domains as PKS domains to both include the monomer in the predicted polymer and enable non-colinear ordering 
Using some of the examples from the other PR, here's the results:
And an unmodified `AHBA`, non-colinear example from NZ_MEAX01000018:
> Add support for treating modules with CAL domains as complete, including monomer/polymer generation

- antismash/detection/hmm_detection/test/test_hmm_detection.py
Fixes a test issue blocking #729, where rule `EXTENDERS` conditions weren't considered for profiles being used.
> hmm_detection: include extender profiles in profile usage test

- antismash/common/secmet/features/module.py
- antismash/detection/nrps_pks_domains/domain_identification.py
- antismash/detection/nrps_pks_domains/module_identification.py
- antismash/modules/cluster_compare/components.py
- antismash/modules/cluster_compare/data_structures.py
- antismash/modules/cluster_compare/test/test_components.py
- antismash/modules/cluster_compare/test/test_data_structures.py
This fixes a crash that occurred when a ClusterCompare query region included a module that used a CAL domain (as introduced in #724), because they were registered as a having a module type of "unknown" in the features.
This has been corrected by adding a new CAL-specific module type in `secmet` and by setting that type in `nrps_pks_domains`.
Adding on that fix, ClusterCompare has been changed from a binary weighting system (i.e. PKS and NRPS) for modules to a system that can take an arbitrary number of types. Initially, these CAL domains have been included in a "generic domains" category, intended for those modules which are too constrained/specific for their own category. This may need to be updated in future, if detection can find a larger variety of these modules.
The building of …
> Update ClusterCompare with modules that use CAL domains 

- antismash/common/signature.py
- antismash/common/test/test_signature.py
Prevents difficult to find issues in whitespace splitting in HMM details files, e.g. #732.
At some point in the future, a clearer file format would be much better, but for the moment this is the simplest fix.
> common.signature: forbid leading and trailing whitespace in signature identifiers

- antismash/config/__init__.py
When using `build_config(..., isolated=True)`, the intent is to not respect config files. However, when running on a machine with many cores (e.g. 256), the tests that use this isolated mode run much, much slower due to contention, i.e. 5-10 times longer than they should.
By changing the isolated mode to also keep the CPU count, this slowdown can be avoided, provided the config file is set.
When running on the command line, this still requires that the user supply, either with a config file or with the relevant argument, the number of CPUs desired.
> Fix extreme slowdowns when running tests on machines with many cores

- antismash/common/hmm_rule_parser/cluster_prediction.py
- antismash/common/hmm_rule_parser/structures.py
- antismash/common/hmm_rule_parser/test/test_cluster_prediction.py
- antismash/detection/hmm_detection/dynamic_profiles/cyanobactin_precursor.py
- antismash/detection/hmm_detection/dynamic_profiles/darobactin_precursor.py
- antismash/detection/hmm_detection/dynamic_profiles/test/test_cyanobactin_precursor.py
- antismash/detection/hmm_detection/dynamic_profiles/test/test_darobactin_precursor.py
- antismash/detection/hmm_detection/dynamic_profiles/test/test_triceptide_precursor.py
- antismash/detection/hmm_detection/dynamic_profiles/triceptide_precursor.py
Changes dynamic profiles to pass in hits from existing HMMs from earlier in detection. This allows for dynamic profiles to avoid duplicating any work in finding the broader applicability before moving on to their more specific checks.
Should replace the base commit in #739, which reintroduced obsolete code and styling.
> common.hmm_rule_parser: allow dynamic profiles access to existing HMMer profile hits

- .gitignore
- Dockerfile
- docker/run_from_podman
The base container doesn't ship with meme-suite installed anymore, as that fails to build on Debian 12. Until we figure out how to drop it properly, shove meme-suite back into the dev container to allow for dev builds.
> Dev container workaround

- antismash/modules/cluster_compare/data_structures.py
- antismash/modules/cluster_compare/ordering.py
- antismash/modules/cluster_compare/test/test_order.py
ClusterCompare only adds an ordering metric when multiple genes in the reference have hits. This raises some single gene hits in the ranking more than they deserve, due to the final ranking using a geometric average of the metrics. This caused rankings like these (the top three hits from a lanthipeptide in NZ_BEWD01000001.1):
By adding a penalty for these, as if there was a second segment, the scores for these kinds of hits are reduced, leading to the top three changing to these:
The final score of venezuelin, since it's used in the example, changes from the initial 0.61 to 0.52, below the lowest of the multi-gene hits against similar class II lanthipeptides within MIBiG. This is true for other single-gene hits in the same example, though they're not shown in the screenshots.
> cluster_compare: penalise single gene hits to multi-gene references

- antismash/detection/nrps_pks_domains/module_identification.py
- antismash/outputs/html/visualisers/nrps_pks_domains.py
Adds detection and drawing for two largely-siderophore-specific NRPS domains, `Interface` and `IBH_Asp`, that were described here: [10.1073/pnas.1903161116](https://www.pnas.org/doi/10.1073/pnas.1903161116). The interface domain is a member of the condensation superfamily, and IBH_Asp is an aspartate beta-hydroxylase that occurs as a fused NRPS domain. 
* The `IBH_Asp` HMM is part of the NRP-metallophore rule. The HMM was converted to `HMMER3/b` but is otherwise identical and uses the same cutoff. The alignment used to make the `Interface` HMM is [here](https://drive.google.com/file/d/13xmgNwytHNMz1Er7QuIqdfbDXjygrRkS/view?usp=share_link) and the cutoff of 150 was assigned on MIBiG clusters and additional NRP metallophore BGCs (roughly TP>180 and FP<120).
* Domains appear in domain/module …
> nrps_pks_domains: add Interface and IBH_Asp domain detection and drawing

- antismash/config/args.py
- antismash/modules/clusterblast/results.py
- antismash/modules/clusterblast/test/test_results.py
- antismash/modules/lassopeptides/specific_analysis.py
- Removes some dead code from lassopeptides
- Changes a number of general command line arguments to have an automatic inverse (e.g. `--no-debug` and `--no-minimal`) to handle cases where users would like to temporarily disable one of these options that they have enabled in a config file
- Fixes an issue in Clusterblast where self-hits weren't being consistently removed, leading to a crash in HTML generation
> Misc small tweaks/fixes

- antismash/config/__init__.py
- antismash/main.py
**Note:** As this sets up the new major release, the config file path has changed from `~/.antismash7.cfg` to `~/.antismash8.cfg`
> chore: Bump version number to 8

- antismash/common/hmm_rule_parser/rule_parser.py
- antismash/common/hmm_rule_parser/test/test_cluster_prediction.py
- antismash/common/hmm_rule_parser/test/test_rule_parser.py
This PR fixes a bug in cluster detection that misses the marking of some core genes. This is due to an assumption that only genes that satisfy the conditions within the cutoff distance _from itself_ will be marked core, despite this not being true in some cases:
This case occurs most often in rules with smaller cutoffs and requires at least three conditions within the rule.
Using `A and B and C` as an example rule and genes laid out like so:
```
AAAAAA          BBBBBB      CCCCCC
|<    cutoff   >|   |<  cutoff  >|
```
`A` here satisfies only the `A and B` portion of the rule, since it's too far from `C`. The opposite is true for `C`, being too far from `A`.
However, `B` is close enough to both and would then form a protocluster, with the core containing only itself, as the other two genes …
> hmm_rule_parser: fix cases of some core genes not being marked

- antismash/modules/terpene/terpene_analysis.py
- antismash/modules/terpene/test/test_terpenes.py
This fixes cases where multiple domains with equal priority are being predicted.
- Changes the get_cluster_prediction function in terpene analysis:
When multiple domains of the same domain type have top priority, all of their sets of products are added to the cluster prediction instead of just one.
The order of the products is always the same.
Asserts that there are no two CompoundGroup instances with the same name.
- Adds a test for the get_cluster_prediction function
> Terpene module: Handle output for domains with same priority

- antismash/common/comparippson/templates/generic.html
- antismash/outputs/html/js.py
Cross-origin genes were being truncated in the visualisation, showing only the pre-origin portion. This has been fixed here.
Page load times were in the order of seconds for some inputs. This turned out to be with RiPPs that had many CompaRiPPson results that generated quite a lot of HTML for the browser to parse.
A test input of six copies of nisin resulted in `index.html` being 2.3 MB, since each input had a precursor with around 130 matches to the antiSMASH-DB. Changing the rendering to only show the first 10 of the hits not shown by default reduced this file size to 383 KB and the load time to less than a second.
Semi-related: antiSMASH-JS has also been updated to 0.16.2 to fix an issue with multi-selecting, but that will apply automatically when running …
> HTML fixes

- antismash/common/record_processing.py
- antismash/common/test/test_record_processing.py
Biopython allows FASTA files to have missing sequence information, e.g.
```
>R1
GCTA
>R2
>R3
TACG
```
This caused a crash in record processing, where the check for WGS records hit an `IndexError` in biopython's sequence indexing, that would previously have been caught in the following check for missing sequence information (which included WGS records with undefined sequences).
The fix here was to also handle that particular index error in the WGS check, leaving the original check for missing sequences in place as a backup for other potential code paths.
> common.record_processing: catch missing sequences in fasta files via biopython

- antismash/common/hmm_rule_parser/cluster_prediction.py
- antismash/common/hmm_rule_parser/test/test_cluster_prediction.py
With a very small circular record/contig, e.g. 38kb long, a protocluster with a cross-origin core could have a neighbourhood (e.g. 20kb each side) applied such that the neighbourhood extension alone was longer than the record. 
This caused the location extension to always a single part full-record location, which then crashed in the check that any protocluster with a cross-origin core must also have a cross-origin neighbourhood.
To solve this, an option to the relevant extension function was added to force the extended location to also be cross-origin, taking the mid-point between the existing location's start and end points as the point of separation.
In order to not appear as a point location (i.e. start and end are equal), the end coordinate is shifted back by one.
This in turn caused …
> Fix a crash when cluster neighbourhoods wrap more than once around the record

- antismash/common/gff_parser.py
- antismash/common/record_processing.py
- antismash/common/test/test_gff_parser.py
A replacement PR for #800 to handle circular annotations in GFF files, fixing #799.
- updates a record's topology when a GFF landmark feature marks it as such
- splits cross-origin feature locations into parts where necessary
- aborts if a record's topology is already explicitly defined (e.g. from an unannotated genbank file) and the GFF file explicitly sets a different topology
- adds the landmark feature as a `source` feature within `secmet.Record`, which previously wasn't added
> common.gff_parser: handle circular annotations in landmark features

- antismash/detection/genefunctions/templates/tailoring.html
Empty output sections are ambiguous as to whether there was a fault or no results. This adds an explicit message to clarify it.
Before:
After:
> genefunctions: show explicit not-found message in HTML rather than empty

- antismash/common/comparippson/templates/generic.html
- antismash/modules/cluster_compare/templates/matrix.html
- antismash/modules/cluster_compare/templates/row.html
- antismash/modules/cluster_compare/templates/single.html
- antismash/modules/clusterblast/templates/clusterblast.html
- antismash/modules/nrps_pks/html_output.py
- antismash/modules/nrps_pks/minowa/base.py
- antismash/modules/nrps_pks/templates/monomers.html
- antismash/modules/nrps_pks/templates/products.html
- antismash/modules/t2pks/templates/sidepanel.html
- antismash/modules/terpene/templates/details.html
- antismash/outputs/html/css/style.scss
- antismash/outputs/html/templates/cds_detail.html
- antismash/outputs/html/templates/footer.html
- antismash/outputs/html/templates/region_table_macros.html
- antismash/outputs/html/templates/regions.html
There's a number of issues that weren't legal HTML, even though they were rendering correctly (so far). Among them are:
- elements without closing tags
- closing tags without opening tags
- mismatched opening and closing tags
- incompatible child elements (e.g. `div` in a `span`)
- etc
Also changes "Confidence" in the HTML overview table to "Similarity Confidence" due to ambiguity around it's application to similarity or the protocluster calls themselves.
> Fixes for non-standard and incorrect HTML formatting

- antismash/detection/hmm_detection/cluster_rules/strict.txt
There's [many](https://antismash-db.secondarymetabolites.org/area.html?record=NC_006322.1&start=3863358&end=3863484) [examples](https://antismash-db.secondarymetabolites.org/area?record=NZ_AUJV01000005&start=40770&end=75703) of `lassopeptide` protoclusters being beside `RRE-containing`, where the RRE hit is to `Stand_Alone_Lasso_RRE`.
It seems simpler to add that RRE profile to the more defined rule in the `EXTENDERS` section, so those "hybrids" will form a single contiguous protocluster instead.
Examples of affected hybrids that now form a single protocluster:
> hmm_detection: add relevant RRE profile as extender for lassopeptides

- antismash/config/args.py
- antismash/main.py
- antismash/outputs/html/templates/header.html
- antismash/outputs/html/templates/regions.html
- antismash/test/integration/integration_antismash.py
The genbank summary file is the single largest file in the output directory, adding up to gigabytes across my high-throughput runs, and none of my downstream tools use it.
I added a flag `--skip-gbk-file` to stop its creation. Modeling it after `--skip-zip-file`, I added two `if` statements to stop creation and to remove the download option from the HTML.
> config: add flag to skip gbk summary writing

- antismash/common/fasta.py
- antismash/common/module_results.py
- antismash/main.py
- antismash/modules/clusterblast/known.py
- antismash/modules/clusterblast/results.py
- antismash/modules/smcog_trees/__init__.py
- antismash/modules/smcog_trees/test/integration_smcogs.py
- antismash/modules/smcog_trees/trees.py
- antismash/outputs/html/js.py
Fixes #811 by adding `ModuleResults.write_outputs()`, which can then handle any output files for a module outside the analysis and in-memory regeneration stages.
The smCOG trees module stores the raw newick tree and not the images themselves, for space considerations. In return it will take some time to regenerate the images themselves (about 1 second/tree, from my tests). This might be significant for large or dense inputs.
No significant timing changes for the clusterblast module, and no changes are made at all for results size.
> Fixes for some output files not being recreated on reuse

- antismash/detection/hmm_detection/data/hmmdetails.txt
- antismash/modules/terpene/data/hmm_properties.json
I noticed that we can lower the cutoff of the TS_Pyr4 profile to enable detection of bacterial homologs (see [doi.org/10.1002/anie.202422270](url), GroF), without noticeably increasing the false positive rate.
I scanned TS_Pyr4 against all proteins in the antismash DB, and it hits some transporters with bitscores <20.
Other than that there is a steep jump to hypothetical proteins with bitscores >70, which I expect to be actual terpene cyclases.
> Extend the detection of Pyr4 type terpene cyclases

- antismash/common/hmm_rule_parser/cluster_prediction.py
- antismash/common/secmet/record.py
- antismash/common/secmet/test/test_secmet.py
This PR fixes crashes due to `CDSCollection` erroneously being passed a `CompoundLocation` that didn't cross the origin (e.g. in RBXO01000001.1). This specific case involves `find_motif_around_anchor` in dynamic profiles, where the anchor gene had a `CompoundLocation` that was extended via `Record.extend_location()`. The equivalent behaviour in cluster prediction was avoided because the resulting output was wrapped in `Record.connect_location()`, which merged all the resulting sections where possible.
Because this can cause problems in such a small amount of inputs, `Record.extend_location()` has been extended rather than just adding the same wrapping.
This change also means that now locations that crossed the origin will have each side extended to the closest edge of the contig, whereas …
> secmet: fix record location extension and make more flexible

- antismash/common/secmet/features/abstract.py
- antismash/common/secmet/features/region/structures.py
- antismash/common/secmet/features/test/test_region.py
- antismash/common/secmet/test/helpers.py
Candidate cluster numbers in region genbanks are adjusted to start counting at 1. This was correct for the candidate cluster features themselves, but not in the references within the region feature's qualifiers.
> Fix for region features in region genbanks not referencing correct candidate numbers

- antismash/common/subprocessing/base.py
- antismash/common/subprocessing/test/integration_subprocessing.py
- antismash/detection/cassis/motifs.py
- 3.12 changed regex boolean evaluation and one of the options (`len(node)`) isn't supported in 3.11
- handles newer macOS system calls for python parallelism failing to serialise our config
- fix test using `cat` that expected the same failure message on both linux and mac
> Misc python 3.12/macos fixes

- antismash/modules/cluster_compare/data/mibig.json
- antismash/outputs/html/templates/mibig_hits_table.html
Fixes #827 and includes a similar change for ClusterCompare.
Also makes the KCB HTML tables open new windows/tabs when following links.
> Fix some links out to MIBiG using old style API

- antismash/common/secmet/record.py
- antismash/common/secmet/test/test_secmet.py
> secmet: fix within_location ignoring overlap arg

- antismash/common/record_processing.py
- antismash/common/test/test_record_processing.py
- antismash/config/args.py
I regularly come across Genbank/RefSeq entries that have poor gene calling with PGAP and PKS genes. I'd normally have to convert the GBK to FASTA, then run antiSMASH over the result.
This PR brings in `--remove-existing-annotations`, which removes every feature from the inputs, allowing other genefinding to be used. The inverse is also accessible, `--no-remove-existing-annotations`, which isn't great naming but I don't have better ideas on that.
> config: add an option to remove all existing annotations from an input

- antismash/common/secmet/features/cdscollection.py
- antismash/common/secmet/features/test/test_cdscollection.py
- antismash/common/secmet/locations.py
- antismash/common/secmet/test/test_locations.py
- antismash/common/secmet/test/test_secmet.py
- antismash/main.py
- antismash/modules/clusterblast/results.py
Fixed crashes:
- in cluster detection for the specific case of splice variants where one variant had a shorter sequence while also a later end coordinate, due to a failure in correctly comparing order of locations
- while directly comparing two locations, while one was compound and the other was not
- in cluster detection when a negative stranded feature caused a cluster to be extended over the origin, due to CDSCollection being too strict with locations in constructors
- (potential fix) one instance of clusterblast output caused an OSError on some systems due to file descriptor leaks (possibly also container file limits), due to the number of files generated per record with many records
Following that last one, a bug was discovered in module output writing that caused a module's results …
> Crash and performance fixes

- antismash/common/gff_parser.py
- antismash/common/secmet/features/cds_feature.py
- antismash/common/secmet/features/test/test_cds_feature.py
- antismash/common/test/test_gff_parser.py
- wraps plain `ValueError` stack traces for GFF feature annotations outside the matching FASTA record
- prevents coercing translations from starting with `M` in cases where the feature's start location is ambiguous
> Small corrections for input handling

- antismash/common/all_orfs.py
- antismash/common/gff_parser.py
- antismash/common/secmet/features/cds_feature.py
- antismash/common/secmet/features/feature.py
- antismash/common/secmet/features/test/test_cds_feature.py
- antismash/common/secmet/features/test/test_feature.py
- antismash/common/secmet/locations.py
- antismash/common/secmet/record.py
- antismash/common/secmet/test/test_circular_conversion.py
- antismash/common/secmet/test/test_locations.py
- antismash/common/secmet/test/test_secmet.py
- antismash/common/subprocessing/diamond.py
- antismash/common/test/test_all_orfs.py
- antismash/common/test/test_gff_parser.py
Diamond raises an error when a protein sequence looks like a nucleotide sequence. This happened with some tiny pseudogenes, where the translation was valid. Diamond can be set to ignore warnings, and since this is the only case covered by that flag (as of now), it's been added.
When an input was circular and the sequence around the origin contained a small, unannotated, gene that were then found in that area with `all_orfs` were then incorrect when the gene was trimmed to the shortest length (i.e. latest start codon). The trimming function didn't consider these cross-origin genes and could result in a gene covering the entire contig, and in some cases crashing due to the translation of that gene being longer than the allowed maximum.
Some inputs crashed inside cluster prediction when a …
> Fixes for odd/unexpected input related errors

- antismash/common/secmet/features/protocluster.py
- antismash/common/secmet/features/test/test_protocluster.py
`Record.from_biopython()` and regeneration of a `Record` from existing JSON results could cause ordering differences when locations were the same. This changes the sort order to include the product name in that situation to make it (more) deterministic.
This can't cover cases where just a location is used as a comparator, but `Record.add_protocluster()` always compares protoclusters with full instances and not just locations.
> secmet: fix protocluster sorting non-determinism when locations are equal

- antismash/common/hmm_rule_parser/rule_parser.py
- antismash/common/hmm_rule_parser/test/test_rule_parser.py
- antismash/detection/hmm_detection/cluster_rules/loose.txt
- antismash/detection/hmm_detection/cluster_rules/strict.txt
`minimum(2, [a, b,c])` is intuitively "a minimum of 2 of a, b, or c".
The actual interpretation is "a minimum of 2 _CDSes_ with a, b, or c".
Some rules have used it with one interpretation and some have used it with the other.
To handle this, the more intuitive naming has been changed to the stricter form where the count is of distinct hits within the group. The existing form, where the number of distinct hits isn't relevant, has been reintroduced as `repeatable`. The decision to rename the existing functionality instead of the stricter version is that the intuitive interpretation will continue to confuse people and not be obvious when testing new rules.
The saccharide rules, `saccharide` and `oligosaccharide`, are now explicitly repeatable. No cluster previously detected will be lost. …
> Split 'minimum' keyword in rules to handle with repeats and without

- antismash/outputs/html/css/style.scss
This reverts commit 456f8bda1ae91b47c6aa815a21eaf3cdfb61b089.
While the gene table size did increase at different browser zoom levels and resolutions, it the scroll functionality would break for both itself and the region overview table.
While the functionality is desired, it will be at a later point where time can be taken for more comprehensive layout/style changes.
> html: revert proportional gene table height limit

- antismash/modules/nrps_pks/orderfinder.py
- antismash/modules/nrps_pks/test/test_orderfinder.py
Fixes #854 and another bug I introduced in 28fe6f7:
- a crash where genes with only a single, cross-CDS module weren't properly checked for which direction the module's shared CDS was connected
- skipping the first CDS' strand in determining the direction of the predicted ordering
> nrps_pks: fix another case of cross-CDS module crashes in orderfinding

- antismash/detection/hmm_detection/cluster_rules/strict.txt
Add a rule to pick up on iterative, non-condensation-domain-containing NRPSes as the one producing AFC-BC11.
> hmm_detection: Add rule for NRPS type III iterative clusters

- antismash/common/gff_parser.py
- antismash/common/hmm_rule_parser/cluster_prediction.py
- antismash/common/record_processing.py
- antismash/common/secmet/features/cds_feature.py
- antismash/common/secmet/features/prepeptide.py
- antismash/common/secmet/features/test/test_cds_feature.py
- antismash/common/secmet/locations.py
- antismash/common/secmet/test/test_locations.py
- antismash/common/subprocessing/memesuite.py
- antismash/common/test/test_gff_parser.py
- antismash/config/args.py
- antismash/detection/hmm_detection/cluster_rules/relaxed.txt
- antismash/detection/hmm_detection/data/hmmdetails.txt
- antismash/detection/hmm_detection/filterhmmdetails.txt
- antismash/detection/hmm_detection/test/test_hmm_detection.py
- antismash/detection/sideloader/data_structures.py
- antismash/main.py
- antismash/modules/nrps_pks/nrpys.py
- antismash/modules/nrps_pks/orderfinder.py
- antismash/modules/nrps_pks/templates/monomers.html
- antismash/modules/nrps_pks/test/test_orderfinder.py
- antismash/outputs/html/visualisers/nrps_pks_domains.py
- setup.py
Prepares for the 8.0.3 release by pulling in, from master, bug fixes and handling changes for previously rejected inputs.
Some cluster predictions will change due to some of the bug fixes, but the rules remain unchanged.
> Prep for 8.0.3 release

- antismash/modules/nrps_pks/templates/monomers.html
Any NRPS A domain that was so strange the prediction tools had nothing to offer were changed to report "No prediction made" as of 0137795e1b5c2da086a4e74ea488dc84a63d6ae5, instead of just a blank section.
I screwed up with the placement of the conditional, which meant the collapser for that scenario had an unclosed div, which in turn removed all displayed results for regions after the one with no prediction. This also caused javascript crashes when ClusterCompare had results for that region and the following regions, due to the selection logic used and assumptions that region elements weren't nested.
> nrps_pks: fix unclosed collapser in substrate sidepanel
