antismash/common/secmet/feature.py, antismash/common/secmet/test/test_secmet.py, antismash/detection/cassis/promoters.py, antismash/detection/cassis/test/test_promoters.py
Bioypthon 1.71 enforces locations having a start lower than the end, this PR fixes issues caused by that.
=> Biopython 1.71 compatibility

antismash/common/layers.py, antismash/main.py, antismash/modules/clusterblast/results.py, antismash/modules/clusterblast/templates/clusterblast.html, antismash/modules/clusterblast/templates/knownclusterblast.html, antismash/modules/clusterblast/templates/subclusterblast.html, antismash/modules/nrps_pks/html_output.py, antismash/modules/nrps_pks/templates/details.html, antismash/outputs/html/generator.py, antismash/outputs/html/index.html, antismash/outputs/html/jnj_generator.html, antismash/outputs/html/js.py, antismash/outputs/html/js/jnj.js, antismash/outputs/html/top_header.html
Fixes multi-record handling in the HTML generation, including clusterblast result files
=> HTML fixes

setup.py
=> setup: Setuptools support Markdown natively now.

Dockerfile, Makefile, antismash/config/__init__.py, antismash/download_databases.py, docker/instance.cfg, docker/run, docker/run_from_docker
We want to run some test containers soon, so make sure we can easily build them.
=> Add docker support

antismash/modules/lanthipeptides/html_output.py, antismash/modules/lanthipeptides/specific_analysis.py
Fixes two issues:
- duplicate Prepeptides being added when two CDS features shared the same precursor
- HTML using the wrong information to find relevant motifs to display in the sidepanel
=> Lanthipeptide fixes

antismash/outputs/html/css/Makefile
=> output/html: make .css files depend on secmet.less as well

.gitignore, Dockerfile, Makefile, antismash/__main__.py, docker/run_from_docker, setup.py
Make it easer to find out what version of antiSMASH is running on the dev site.
=> Dev deploy improvements

antismash/outputs/html/js/jsdomain.js
Add the two TIGRFAMs models describing NRPS-related domains.
Also fix a labeling issue I discovered along the way.
=> Detect weird NRPS domains

antismash/detection/genefunctions/smcogs.py, antismash/detection/genefunctions/test/integration_smcogs.py, antismash/outputs/html/templates/cds_detail.html
Some minor fixes for things I found when playing with the new alpha yesterday evening.
=> Small html fixes

antismash/outputs/html/images/fungi_antismash_logo.svg
=> outputs/html: Add missing fungismash logo

antismash/common/errors.py, antismash/common/gff_parser.py, antismash/common/record_processing.py, antismash/common/secmet/test/helpers.py, antismash/common/test/test_gff_parser.py, antismash/common/test/test_record_processing.py
- adds a custom error class for simplified catching of bad inputs and uses it where relevant
- refactors some of the input parsing code that was more complex than it should have been
- fixes an issue that all CDS_motif features were being stripped, when only ones created previously by antiSMASH should have been stripped
=> Input processing cleanup

antismash/detection/genefinding/run_glimmerhmm.py
=> genefinding: Don't throw an exception when GlimmerHMM fails to find genes

README.md
=> README: Point to antiSMASH install docs from the README

antismash/common/record_processing.py
Fixes Biopython stripping invalid locations from features and pretending they have no location.
Also catches mismatches between length of sequence provided and declared length of sequence, because there's almost certainly something wrong there.
=> common.record_processing: convert some biopython warnings to exceptions

antismash/common/secmet/features/candidate_cluster.py, antismash/main.py
- region file cleanup was still attempting to use filenames with `cluster` instead of `region
- removed some duplicate code in conversion to biopython features for candidate clusters
=> Small fixes

antismash/main.py
=> chore: Bump version to 5.0.0

.github/no-response.yml
=> chore: Add config for no-response probot plugin

antismash/detection/hmm_detection/data/hmmdetails.txt
=> hmm_detection: Adjust Chal_sti_synth_* profile cutoffs to cutoff values given in files

antismash/common/hmmer.py
=> common.hmmer: remove broken check

antismash/main.py
=> Remove Unused Args from Function Doc

antismash/modules/nrps_pks/orderfinder.py, antismash/modules/nrps_pks/smiles_generator.py, antismash/modules/nrps_pks/specific_analysis.py, antismash/modules/nrps_pks/test/test_smiles_generator.py
Uses module modification domains to alter SMILES generation, adding methyl groups when possible for relevant methylation domains.
Includes a refactor of the SMILES logic to pass the relevant data in and removes some inaccurate edge cases at the same time.
=> SMILES generation improvements

antismash/common/secmet/features/region.py, antismash/common/secmet/features/test/test_region.py
Fixes #218.
Prepeptides annotate the leader and tail component locations in qualifiers so they can be rebuilt from a genbank file, however they weren't properly adjusted when generating per-region genbank files.
=> secmet: fix region genbank outputs not adjusting locations in qualifiers

antismash/main.py
=> main: Bump the antiSMASH version logging line to INFO level

antismash/common/subprocessing/java.py, antismash/common/subprocessing/test/test_java.py, antismash/main.py
=> Fix the java version detection when _JAVA_OPTIONS are set

antismash/modules/nrps_pks/orderfinder.py, antismash/modules/nrps_pks/results.py, antismash/modules/nrps_pks/templates/products.html, antismash/modules/nrps_pks/test/integration/integration_nrps_pks.py
Also removes CDS features without complete modules from the colinearity direction check.
=> Display nonlinear pks ordering in output

antismash/detection/nrps_pks_domains/domain_identification.py, antismash/modules/nrps_pks/orderfinder.py
=> Last minute fixes

antismash/main.py
=> chore: bump antiSMASH version to 6.0.0alpha1

antismash/modules/clusterblast/__init__.py
=> clusterblast: Properly detect magic value used during Docker lite image build

antismash/common/secmet/features/prepeptide.py, antismash/config/__init__.py, antismash/config/args.py, antismash/download_databases.py, antismash/main.py, antismash/modules/nrps_pks/orderfinder.py, setup.py
mypy 0.630 is incompatible with python 3.8. Some extra type hints were required in order to update to mypy 0.790
=> Update mypy to a py3.8 compatible version

antismash/common/secmet/record.py
=> secmet: ds-DNA is also a valid molecule type

antismash/main.py
=> chore: bump version to 6.0.0

antismash/download_databases.py, antismash/modules/clusterblast/core.py, antismash/modules/clusterblast/test/test_clusterblast.py, antismash/modules/lanthipeptides/specific_analysis.py, antismash/modules/lanthipeptides/templates/details.html, antismash/modules/lanthipeptides/templates/sidepanel.html, antismash/modules/lanthipeptides/test/integration_lanthipeptides.py, antismash/modules/lanthipeptides/test/test_specific_analysis.py, antismash/modules/lassopeptides/specific_analysis.py, antismash/modules/lassopeptides/templates/details.html, antismash/modules/lassopeptides/templates/sidepanel.html, antismash/modules/lassopeptides/test/test_specific_analysis.py, antismash/modules/sactipeptides/specific_analysis.py, antismash/modules/sactipeptides/templates/details.html, antismash/modules/sactipeptides/templates/sidepanel.html, antismash/modules/sactipeptides/test/integration_sactipeptides.py, antismash/modules/thiopeptides/specific_analysis.py, antismash/modules/thiopeptides/templates/details.html, antismash/modules/thiopeptides/templates/sidepanel.html, antismash/modules/thiopeptides/test/test_thio_specific_analysis.py, setup.py
This is basically PR #373 for 6-0-stable
=> Fast-forward 6-0-stable branch

antismash/main.py
=> chore: bump version to 6.0.1

antismash/modules/clusterblast/test/integration_clusterblast.py
This is due to diamond 2 changing scoring results. Scores themselves seem to be only subtly changed, in the range of 0.1% from version 0.9, but this has resulted in more hits for clusterblast.
Tested with 2.0.9, specifically, as that's shipped with Debian Bullseye.
=> clusterblast: adjust tests to handle newer diamond versions

.github/workflows/pylint_issue_reporter.yml
Add a github action that runs over pull requests and generates a report of resolved/added issues.
=> chore: add a github action for comparing pull requests

antismash/outputs/html/visualisers/bubble_view.py
Candidate clusters can contain only half of a cross-CDS module even when the CDS features are consecutive (e.g. NZ_CP020102.1 in the region 1,763,795 - 1,869,041). When drawing these kind of modules, it should a) not crash, and b) not show the module as complete when the other half is not included in that particular drawing subset.
This PR trims modules such as these down to the domains within the candidate and marks the resulting truncated module as incomplete for the purposes of drawing that particular candidate cluster result.
=> Improvements to bubble view and cross-CDS modules

antismash/outputs/html/generator.py
=> outputs/html: Honour output_basename in the HTML page title

antismash/common/secmet/features/region.py, antismash/modules/clusterblast/html_output.py, antismash/support/genefinding/run_prodigal.py
Changes some leftover wording of 'cluster' to 'region' in outputs.
Simplifies FASTA generation for prodigal input (incidentally fixes a crash that could occur with seqio including spaces in outputs for some very specific inputs).
=> Minor fixes

antismash/common/secmet/features/antismash_domain.py, antismash/common/secmet/features/antismash_feature.py, antismash/common/secmet/features/cds_feature.py, antismash/common/secmet/features/cds_motif.py, antismash/common/secmet/features/feature.py, antismash/common/secmet/features/gene.py, antismash/common/secmet/features/pfam_domain.py, antismash/common/secmet/features/prepeptide.py, antismash/common/secmet/features/test/test_feature.py, antismash/common/secmet/record.py, antismash/detection/nrps_pks_domains/modular_domain.py, antismash/detection/tigrfam/tigr_domain.py, antismash/main.py, antismash/modules/rrefinder/rre_domain.py, setup.py
=> Prepare 6.1.1

antismash/common/secmet/record.py
Vastly simplifies any subclassing of `Record`.
=> Changes to support inheritance

antismash/common/subprocessing/muscle.py
=> common.subprocessing: make muscle version check case insenstive

antismash/detection/hmm_detection/data/extract_details.py, antismash/detection/hmm_detection/test/test_extract_details.py, antismash/detection/nrps_pks_domains/domain_identification.py
* HMM detail extraction script
* Fix for an assert triggered by `run_mibig.py` so the log contains a useful error message.
=> Misc fixes, try 2

antismash/common/hmmer.py, antismash/common/test/test_hmmer.py, antismash/detection/cluster_hmmer/__init__.py, antismash/detection/full_hmmer/__init__.py, antismash/detection/genefunctions/__init__.py, antismash/download_databases.py, antismash/test/integration/integration_antismash.py
- Fixes an issue brought in by #485 that commented out most databases.
- Adds better handling to prerequisite checks for building docker containers where the database directory is mounted at runtime.
- Adds some tests to ensure that trying to prepare data in a runtime mounted directory is caught early on.
=> Database updates

Dockerfile, Makefile
=> chore: Make building containers in podman easier

antismash/common/hmmscan_refinement.py, antismash/common/path.py, antismash/common/pfamdb.py, antismash/common/secmet/features/antismash_domain.py, antismash/common/secmet/qualifiers/nrps_pks.py, antismash/common/secmet/qualifiers/test/test_nrpspks.py, antismash/common/secmet/test/test_secmet.py, antismash/common/subprocessing/hmmscan.py, antismash/common/test/helpers.py, antismash/common/test/test_hmmscan_refinement.py, antismash/common/test/test_pfamdb.py, antismash/detection/nrps_pks_domains/domain_drawing.py, antismash/detection/nrps_pks_domains/domain_identification.py, antismash/detection/nrps_pks_domains/modular_domain.py, antismash/detection/nrps_pks_domains/module_identification.py, antismash/detection/nrps_pks_domains/test/test_domain_identification.py, antismash/detection/nrps_pks_domains/test/test_modular_domain.py, antismash/detection/nrps_pks_domains/test/test_modules.py, antismash/modules/nrps_pks/html_output.py, antismash/modules/nrps_pks/results.py, antismash/modules/nrps_pks/test/test_stachelhaus.py, antismash/outputs/html/visualisers/bubble_view.py
Changes NRPS/PKS qualifier and modular domains to allow for arbitrary depths of sub-types.
=> NRPS/PKS preparation work for transATor inclusion

antismash/modules/nrps_pks/parsers.py, antismash/modules/nrps_pks/test/test_parsers.py
=> nrps_pks: Make sure ALLOWABLE_PREDICTION_CHARACTERS covers all known substrate Norine names

.github/workflows/pylint_issue_reporter.yml
Also explicitly checks out the merge commit for linting PRs.
=> chore: handle more workflow deprecations

antismash/common/secmet/record.py, antismash/common/secmet/test/test_secmet.py, antismash/detection/sideloader/general.py, antismash/detection/sideloader/test/test_general.py
=> Handle combinations of renaming long record identifiers and sideloading results

.gitignore
A prerequisite for #698, since the action it's introducing is clever enough to undo these changes when in the same PR.
=> chore: extend git ignore exceptions for known cases

antismash/detection/hmm_detection/cluster_rules/loose.txt, antismash/detection/hmm_detection/cluster_rules/strict.txt
Add a role for polyhalogenated pyrrole
=> Polyhalogenated pyrrole rule

antismash/common/record_processing.py
Message now includes the record ID
=> record_processing: improve INFO on no genes found

antismash/detection/hmm_detection/cluster_rules/loose.txt, antismash/detection/hmm_detection/cluster_rules/relaxed.txt
=> hmm_detection: move fungal-RiPP-like from relaxed to loose

antismash/common/secmet/features/feature.py, antismash/common/secmet/locations.py, antismash/common/subprocessing/test/integration_subprocessing.py
So far just some fixes for python versions > 3.11, might collect some more things.
=> Misc fixes

antismash/modules/nrps_pks/orderfinder.py, antismash/modules/nrps_pks/test/test_orderfinder.py
Colinear orderfinding of NRPS/PKS candidate had issues where CDS features with cross-CDS modules were in the forward strand and there was also a CDS in the reverse strand with a module containing a terminal domain.
The previous logic would flip the order of all genes when that reverse strand terminal was found, which then inverted the order of those chains of CDS features with cross-CDS modules, leading to some very wrong results.
For example, here is CP102510 from 70,000 to 14,0000, with the reverse strand PKS block containing a terminal and the right hand NRPS side being a chain of three CDS features joined by cross-CDS modules:
With `JIW86_40515` and `JIW86_40520` being represented twice, each with only some of their domains.
After the fix, it's now correct:
This particular example is …
=> nrps_pks: fix invalid colinear ordering when reversing cross-CDS modules
